package io.github.gonbei774.calisthenicsmemory.data.catalogue

import io.github.gonbei774.calisthenicsmemory.R
import io.github.gonbei774.calisthenicsmemory.data.v2.ExerciseKind.DYNAMIC
import io.github.gonbei774.calisthenicsmemory.data.v2.ExerciseKind.ISOMETRIC
import io.github.gonbei774.calisthenicsmemory.data.v2.Laterality.BILATERAL
import io.github.gonbei774.calisthenicsmemory.data.v2.Laterality.UNILATERAL

/**
 * Catalogue v1: the core chains (ADR 0006). Names, descriptions, cues and standards are written
 * for this project; see docs/catalogue-sources.md. Text lives in res/values/catalogue_strings.xml.
 * CatalogueTest checks the rules every entry must follow.
 *
 * Generated by scripts/catalogue/generate_catalogue.py from catalogue_spec.py: edit the spec,
 * then regenerate, rather than editing this file.
 */
object Catalogue {
    val chains: List<CatalogueChain> = listOf(
        CatalogueChain(
            "push", R.string.cat_chain_push, MovementPattern.HORIZONTAL_PUSH,
            listOf(
                CatalogueStep(
                    "push.wall", "push", R.string.cat_push_wall, R.string.cat_push_wall_desc, R.string.cat_push_wall_cues,
                    DYNAMIC, BILATERAL, difficulty = 1,
                    working = Standard(3, 10), moveOn = Standard(3, 20),
                    primaryMuscles = setOf(Muscle.CHEST), secondaryMuscles = setOf(Muscle.SHOULDERS, Muscle.TRICEPS),
                    equipment = emptySet(),
                ),
                CatalogueStep(
                    "push.incline", "push", R.string.cat_push_incline, R.string.cat_push_incline_desc, R.string.cat_push_incline_cues,
                    DYNAMIC, BILATERAL, difficulty = 2,
                    working = Standard(3, 8), moveOn = Standard(3, 15),
                    primaryMuscles = setOf(Muscle.CHEST), secondaryMuscles = setOf(Muscle.SHOULDERS, Muscle.TRICEPS),
                    equipment = setOf(Equipment.BENCH),
                ),
                CatalogueStep(
                    "push.knee", "push", R.string.cat_push_knee, R.string.cat_push_knee_desc, R.string.cat_push_knee_cues,
                    DYNAMIC, BILATERAL, difficulty = 2,
                    working = Standard(3, 8), moveOn = Standard(3, 15),
                    primaryMuscles = setOf(Muscle.CHEST), secondaryMuscles = setOf(Muscle.SHOULDERS, Muscle.TRICEPS),
                    equipment = emptySet(),
                ),
                CatalogueStep(
                    "push.full", "push", R.string.cat_push_full, R.string.cat_push_full_desc, R.string.cat_push_full_cues,
                    DYNAMIC, BILATERAL, difficulty = 3,
                    working = Standard(3, 5), moveOn = Standard(3, 12),
                    primaryMuscles = setOf(Muscle.CHEST), secondaryMuscles = setOf(Muscle.SHOULDERS, Muscle.TRICEPS, Muscle.ABDOMINALS),
                    equipment = emptySet(),
                ),
                CatalogueStep(
                    "push.diamond", "push", R.string.cat_push_diamond, R.string.cat_push_diamond_desc, R.string.cat_push_diamond_cues,
                    DYNAMIC, BILATERAL, difficulty = 4,
                    working = Standard(3, 5), moveOn = Standard(3, 10),
                    primaryMuscles = setOf(Muscle.TRICEPS), secondaryMuscles = setOf(Muscle.CHEST, Muscle.SHOULDERS),
                    equipment = emptySet(),
                ),
                CatalogueStep(
                    "push.decline", "push", R.string.cat_push_decline, R.string.cat_push_decline_desc, R.string.cat_push_decline_cues,
                    DYNAMIC, BILATERAL, difficulty = 4,
                    working = Standard(3, 5), moveOn = Standard(3, 10),
                    primaryMuscles = setOf(Muscle.CHEST, Muscle.SHOULDERS), secondaryMuscles = setOf(Muscle.TRICEPS),
                    equipment = setOf(Equipment.BENCH),
                ),
                CatalogueStep(
                    "push.archer", "push", R.string.cat_push_archer, R.string.cat_push_archer_desc, R.string.cat_push_archer_cues,
                    DYNAMIC, UNILATERAL, difficulty = 6,
                    working = Standard(3, 4), moveOn = Standard(3, 8),
                    primaryMuscles = setOf(Muscle.CHEST), secondaryMuscles = setOf(Muscle.TRICEPS, Muscle.SHOULDERS),
                    equipment = emptySet(),
                ),
                CatalogueStep(
                    "push.one_arm", "push", R.string.cat_push_one_arm, R.string.cat_push_one_arm_desc, R.string.cat_push_one_arm_cues,
                    DYNAMIC, UNILATERAL, difficulty = 8,
                    working = Standard(3, 2), moveOn = Standard(3, 6),
                    primaryMuscles = setOf(Muscle.CHEST, Muscle.TRICEPS), secondaryMuscles = setOf(Muscle.SHOULDERS, Muscle.ABDOMINALS),
                    equipment = emptySet(),
                ),
            ),
        ),
        CatalogueChain(
            "vpush", R.string.cat_chain_vpush, MovementPattern.VERTICAL_PUSH,
            listOf(
                CatalogueStep(
                    "vpush.pike", "vpush", R.string.cat_vpush_pike, R.string.cat_vpush_pike_desc, R.string.cat_vpush_pike_cues,
                    DYNAMIC, BILATERAL, difficulty = 3,
                    working = Standard(3, 5), moveOn = Standard(3, 10),
                    primaryMuscles = setOf(Muscle.SHOULDERS), secondaryMuscles = setOf(Muscle.TRICEPS, Muscle.CHEST),
                    equipment = emptySet(),
                ),
                CatalogueStep(
                    "vpush.elevated_pike", "vpush", R.string.cat_vpush_elevated_pike, R.string.cat_vpush_elevated_pike_desc, R.string.cat_vpush_elevated_pike_cues,
                    DYNAMIC, BILATERAL, difficulty = 4,
                    working = Standard(3, 5), moveOn = Standard(3, 10),
                    primaryMuscles = setOf(Muscle.SHOULDERS), secondaryMuscles = setOf(Muscle.TRICEPS),
                    equipment = setOf(Equipment.BENCH),
                ),
                CatalogueStep(
                    "vpush.wall_hold", "vpush", R.string.cat_vpush_wall_hold, R.string.cat_vpush_wall_hold_desc, R.string.cat_vpush_wall_hold_cues,
                    ISOMETRIC, BILATERAL, difficulty = 4,
                    working = Standard(3, 15), moveOn = Standard(3, 45),
                    primaryMuscles = setOf(Muscle.SHOULDERS), secondaryMuscles = setOf(Muscle.TRICEPS, Muscle.ABDOMINALS),
                    equipment = setOf(Equipment.WALL),
                ),
                CatalogueStep(
                    "vpush.wall_negative", "vpush", R.string.cat_vpush_wall_negative, R.string.cat_vpush_wall_negative_desc, R.string.cat_vpush_wall_negative_cues,
                    DYNAMIC, BILATERAL, difficulty = 6,
                    working = Standard(3, 3), moveOn = Standard(3, 6),
                    primaryMuscles = setOf(Muscle.SHOULDERS, Muscle.TRICEPS), secondaryMuscles = emptySet(),
                    equipment = setOf(Equipment.WALL),
                ),
                CatalogueStep(
                    "vpush.wall_hspu", "vpush", R.string.cat_vpush_wall_hspu, R.string.cat_vpush_wall_hspu_desc, R.string.cat_vpush_wall_hspu_cues,
                    DYNAMIC, BILATERAL, difficulty = 7,
                    working = Standard(3, 3), moveOn = Standard(3, 8),
                    primaryMuscles = setOf(Muscle.SHOULDERS, Muscle.TRICEPS), secondaryMuscles = setOf(Muscle.TRAPS),
                    equipment = setOf(Equipment.WALL),
                ),
            ),
        ),
        CatalogueChain(
            "dip", R.string.cat_chain_dip, MovementPattern.VERTICAL_PUSH,
            listOf(
                CatalogueStep(
                    "dip.bench", "dip", R.string.cat_dip_bench, R.string.cat_dip_bench_desc, R.string.cat_dip_bench_cues,
                    DYNAMIC, BILATERAL, difficulty = 2,
                    working = Standard(3, 8), moveOn = Standard(3, 15),
                    primaryMuscles = setOf(Muscle.TRICEPS), secondaryMuscles = setOf(Muscle.CHEST, Muscle.SHOULDERS),
                    equipment = setOf(Equipment.BENCH),
                ),
                CatalogueStep(
                    "dip.support", "dip", R.string.cat_dip_support, R.string.cat_dip_support_desc, R.string.cat_dip_support_cues,
                    ISOMETRIC, BILATERAL, difficulty = 3,
                    working = Standard(3, 10), moveOn = Standard(3, 30),
                    primaryMuscles = setOf(Muscle.TRICEPS, Muscle.SHOULDERS), secondaryMuscles = setOf(Muscle.CHEST),
                    equipment = setOf(Equipment.PARALLEL_BARS),
                ),
                CatalogueStep(
                    "dip.negative", "dip", R.string.cat_dip_negative, R.string.cat_dip_negative_desc, R.string.cat_dip_negative_cues,
                    DYNAMIC, BILATERAL, difficulty = 4,
                    working = Standard(3, 3), moveOn = Standard(3, 6),
                    primaryMuscles = setOf(Muscle.CHEST, Muscle.TRICEPS), secondaryMuscles = setOf(Muscle.SHOULDERS),
                    equipment = setOf(Equipment.PARALLEL_BARS),
                ),
                CatalogueStep(
                    "dip.full", "dip", R.string.cat_dip_full, R.string.cat_dip_full_desc, R.string.cat_dip_full_cues,
                    DYNAMIC, BILATERAL, difficulty = 5,
                    working = Standard(3, 5), moveOn = Standard(3, 10),
                    primaryMuscles = setOf(Muscle.CHEST, Muscle.TRICEPS), secondaryMuscles = setOf(Muscle.SHOULDERS),
                    equipment = setOf(Equipment.PARALLEL_BARS),
                ),
            ),
        ),
        CatalogueChain(
            "pull", R.string.cat_chain_pull, MovementPattern.VERTICAL_PULL,
            listOf(
                CatalogueStep(
                    "pull.dead_hang", "pull", R.string.cat_pull_dead_hang, R.string.cat_pull_dead_hang_desc, R.string.cat_pull_dead_hang_cues,
                    ISOMETRIC, BILATERAL, difficulty = 1,
                    working = Standard(3, 15), moveOn = Standard(3, 45),
                    primaryMuscles = setOf(Muscle.FOREARMS), secondaryMuscles = setOf(Muscle.LATS, Muscle.SHOULDERS),
                    equipment = setOf(Equipment.PULL_UP_BAR),
                ),
                CatalogueStep(
                    "pull.scapular", "pull", R.string.cat_pull_scapular, R.string.cat_pull_scapular_desc, R.string.cat_pull_scapular_cues,
                    DYNAMIC, BILATERAL, difficulty = 2,
                    working = Standard(3, 6), moveOn = Standard(3, 12),
                    primaryMuscles = setOf(Muscle.LATS, Muscle.MIDDLE_BACK), secondaryMuscles = setOf(Muscle.TRAPS),
                    equipment = setOf(Equipment.PULL_UP_BAR),
                ),
                CatalogueStep(
                    "pull.negative", "pull", R.string.cat_pull_negative, R.string.cat_pull_negative_desc, R.string.cat_pull_negative_cues,
                    DYNAMIC, BILATERAL, difficulty = 3,
                    working = Standard(3, 3), moveOn = Standard(3, 6),
                    primaryMuscles = setOf(Muscle.LATS), secondaryMuscles = setOf(Muscle.BICEPS, Muscle.MIDDLE_BACK),
                    equipment = setOf(Equipment.PULL_UP_BAR),
                ),
                CatalogueStep(
                    "pull.band", "pull", R.string.cat_pull_band, R.string.cat_pull_band_desc, R.string.cat_pull_band_cues,
                    DYNAMIC, BILATERAL, difficulty = 3,
                    working = Standard(3, 5), moveOn = Standard(3, 10),
                    primaryMuscles = setOf(Muscle.LATS), secondaryMuscles = setOf(Muscle.BICEPS, Muscle.MIDDLE_BACK),
                    equipment = setOf(Equipment.PULL_UP_BAR, Equipment.RESISTANCE_BAND),
                ),
                CatalogueStep(
                    "pull.chin", "pull", R.string.cat_pull_chin, R.string.cat_pull_chin_desc, R.string.cat_pull_chin_cues,
                    DYNAMIC, BILATERAL, difficulty = 4,
                    working = Standard(3, 4), moveOn = Standard(3, 8),
                    primaryMuscles = setOf(Muscle.LATS, Muscle.BICEPS), secondaryMuscles = setOf(Muscle.MIDDLE_BACK),
                    equipment = setOf(Equipment.PULL_UP_BAR),
                ),
                CatalogueStep(
                    "pull.full", "pull", R.string.cat_pull_full, R.string.cat_pull_full_desc, R.string.cat_pull_full_cues,
                    DYNAMIC, BILATERAL, difficulty = 5,
                    working = Standard(3, 4), moveOn = Standard(3, 8),
                    primaryMuscles = setOf(Muscle.LATS), secondaryMuscles = setOf(Muscle.BICEPS, Muscle.MIDDLE_BACK, Muscle.FOREARMS),
                    equipment = setOf(Equipment.PULL_UP_BAR),
                ),
                CatalogueStep(
                    "pull.archer", "pull", R.string.cat_pull_archer, R.string.cat_pull_archer_desc, R.string.cat_pull_archer_cues,
                    DYNAMIC, UNILATERAL, difficulty = 7,
                    working = Standard(3, 3), moveOn = Standard(3, 6),
                    primaryMuscles = setOf(Muscle.LATS), secondaryMuscles = setOf(Muscle.BICEPS, Muscle.FOREARMS),
                    equipment = setOf(Equipment.PULL_UP_BAR),
                ),
                CatalogueStep(
                    "pull.one_arm_negative", "pull", R.string.cat_pull_one_arm_negative, R.string.cat_pull_one_arm_negative_desc, R.string.cat_pull_one_arm_negative_cues,
                    DYNAMIC, UNILATERAL, difficulty = 8,
                    working = Standard(3, 2), moveOn = Standard(3, 4),
                    primaryMuscles = setOf(Muscle.LATS, Muscle.BICEPS), secondaryMuscles = setOf(Muscle.FOREARMS),
                    equipment = setOf(Equipment.PULL_UP_BAR),
                ),
                CatalogueStep(
                    "pull.one_arm", "pull", R.string.cat_pull_one_arm, R.string.cat_pull_one_arm_desc, R.string.cat_pull_one_arm_cues,
                    DYNAMIC, UNILATERAL, difficulty = 9,
                    working = Standard(3, 1), moveOn = Standard(3, 3),
                    primaryMuscles = setOf(Muscle.LATS, Muscle.BICEPS), secondaryMuscles = setOf(Muscle.FOREARMS, Muscle.MIDDLE_BACK),
                    equipment = setOf(Equipment.PULL_UP_BAR),
                ),
            ),
        ),
        CatalogueChain(
            "row", R.string.cat_chain_row, MovementPattern.HORIZONTAL_PULL,
            listOf(
                CatalogueStep(
                    "row.incline", "row", R.string.cat_row_incline, R.string.cat_row_incline_desc, R.string.cat_row_incline_cues,
                    DYNAMIC, BILATERAL, difficulty = 1,
                    working = Standard(3, 8), moveOn = Standard(3, 15),
                    primaryMuscles = setOf(Muscle.MIDDLE_BACK, Muscle.LATS), secondaryMuscles = setOf(Muscle.BICEPS),
                    equipment = setOf(Equipment.LOW_BAR),
                ),
                CatalogueStep(
                    "row.horizontal", "row", R.string.cat_row_horizontal, R.string.cat_row_horizontal_desc, R.string.cat_row_horizontal_cues,
                    DYNAMIC, BILATERAL, difficulty = 3,
                    working = Standard(3, 5), moveOn = Standard(3, 12),
                    primaryMuscles = setOf(Muscle.MIDDLE_BACK, Muscle.LATS), secondaryMuscles = setOf(Muscle.BICEPS, Muscle.SHOULDERS),
                    equipment = setOf(Equipment.LOW_BAR),
                ),
                CatalogueStep(
                    "row.feet_elevated", "row", R.string.cat_row_feet_elevated, R.string.cat_row_feet_elevated_desc, R.string.cat_row_feet_elevated_cues,
                    DYNAMIC, BILATERAL, difficulty = 4,
                    working = Standard(3, 5), moveOn = Standard(3, 12),
                    primaryMuscles = setOf(Muscle.MIDDLE_BACK, Muscle.LATS), secondaryMuscles = setOf(Muscle.BICEPS),
                    equipment = setOf(Equipment.LOW_BAR, Equipment.BENCH),
                ),
                CatalogueStep(
                    "row.archer", "row", R.string.cat_row_archer, R.string.cat_row_archer_desc, R.string.cat_row_archer_cues,
                    DYNAMIC, UNILATERAL, difficulty = 6,
                    working = Standard(3, 4), moveOn = Standard(3, 8),
                    primaryMuscles = setOf(Muscle.MIDDLE_BACK, Muscle.LATS), secondaryMuscles = setOf(Muscle.BICEPS),
                    equipment = setOf(Equipment.LOW_BAR),
                ),
                CatalogueStep(
                    "row.one_arm", "row", R.string.cat_row_one_arm, R.string.cat_row_one_arm_desc, R.string.cat_row_one_arm_cues,
                    DYNAMIC, UNILATERAL, difficulty = 7,
                    working = Standard(3, 3), moveOn = Standard(3, 8),
                    primaryMuscles = setOf(Muscle.MIDDLE_BACK, Muscle.LATS), secondaryMuscles = setOf(Muscle.BICEPS, Muscle.ABDOMINALS),
                    equipment = setOf(Equipment.LOW_BAR),
                ),
            ),
        ),
        CatalogueChain(
            "squat", R.string.cat_chain_squat, MovementPattern.SQUAT,
            listOf(
                CatalogueStep(
                    "squat.assisted", "squat", R.string.cat_squat_assisted, R.string.cat_squat_assisted_desc, R.string.cat_squat_assisted_cues,
                    DYNAMIC, BILATERAL, difficulty = 1,
                    working = Standard(3, 10), moveOn = Standard(3, 20),
                    primaryMuscles = setOf(Muscle.QUADRICEPS), secondaryMuscles = setOf(Muscle.GLUTES, Muscle.HAMSTRINGS),
                    equipment = emptySet(),
                ),
                CatalogueStep(
                    "squat.full", "squat", R.string.cat_squat_full, R.string.cat_squat_full_desc, R.string.cat_squat_full_cues,
                    DYNAMIC, BILATERAL, difficulty = 2,
                    working = Standard(3, 10), moveOn = Standard(3, 25),
                    primaryMuscles = setOf(Muscle.QUADRICEPS), secondaryMuscles = setOf(Muscle.GLUTES, Muscle.HAMSTRINGS),
                    equipment = emptySet(),
                ),
                CatalogueStep(
                    "squat.split", "squat", R.string.cat_squat_split, R.string.cat_squat_split_desc, R.string.cat_squat_split_cues,
                    DYNAMIC, UNILATERAL, difficulty = 3,
                    working = Standard(3, 8), moveOn = Standard(3, 15),
                    primaryMuscles = setOf(Muscle.QUADRICEPS, Muscle.GLUTES), secondaryMuscles = setOf(Muscle.HAMSTRINGS),
                    equipment = emptySet(),
                ),
                CatalogueStep(
                    "squat.bulgarian", "squat", R.string.cat_squat_bulgarian, R.string.cat_squat_bulgarian_desc, R.string.cat_squat_bulgarian_cues,
                    DYNAMIC, UNILATERAL, difficulty = 4,
                    working = Standard(3, 6), moveOn = Standard(3, 12),
                    primaryMuscles = setOf(Muscle.QUADRICEPS, Muscle.GLUTES), secondaryMuscles = setOf(Muscle.HAMSTRINGS),
                    equipment = setOf(Equipment.BENCH),
                ),
                CatalogueStep(
                    "squat.assisted_pistol", "squat", R.string.cat_squat_assisted_pistol, R.string.cat_squat_assisted_pistol_desc, R.string.cat_squat_assisted_pistol_cues,
                    DYNAMIC, UNILATERAL, difficulty = 5,
                    working = Standard(3, 5), moveOn = Standard(3, 10),
                    primaryMuscles = setOf(Muscle.QUADRICEPS, Muscle.GLUTES), secondaryMuscles = setOf(Muscle.HAMSTRINGS, Muscle.ABDOMINALS),
                    equipment = emptySet(),
                ),
                CatalogueStep(
                    "squat.shrimp", "squat", R.string.cat_squat_shrimp, R.string.cat_squat_shrimp_desc, R.string.cat_squat_shrimp_cues,
                    DYNAMIC, UNILATERAL, difficulty = 6,
                    working = Standard(3, 3), moveOn = Standard(3, 8),
                    primaryMuscles = setOf(Muscle.QUADRICEPS, Muscle.GLUTES), secondaryMuscles = setOf(Muscle.HAMSTRINGS),
                    equipment = emptySet(),
                ),
                CatalogueStep(
                    "squat.pistol", "squat", R.string.cat_squat_pistol, R.string.cat_squat_pistol_desc, R.string.cat_squat_pistol_cues,
                    DYNAMIC, UNILATERAL, difficulty = 7,
                    working = Standard(3, 3), moveOn = Standard(3, 8),
                    primaryMuscles = setOf(Muscle.QUADRICEPS, Muscle.GLUTES), secondaryMuscles = setOf(Muscle.HAMSTRINGS, Muscle.ABDOMINALS),
                    equipment = emptySet(),
                ),
            ),
        ),
        CatalogueChain(
            "hinge", R.string.cat_chain_hinge, MovementPattern.HINGE,
            listOf(
                CatalogueStep(
                    "hinge.bridge", "hinge", R.string.cat_hinge_bridge, R.string.cat_hinge_bridge_desc, R.string.cat_hinge_bridge_cues,
                    DYNAMIC, BILATERAL, difficulty = 1,
                    working = Standard(3, 10), moveOn = Standard(3, 20),
                    primaryMuscles = setOf(Muscle.GLUTES), secondaryMuscles = setOf(Muscle.HAMSTRINGS, Muscle.LOWER_BACK),
                    equipment = emptySet(),
                ),
                CatalogueStep(
                    "hinge.single_bridge", "hinge", R.string.cat_hinge_single_bridge, R.string.cat_hinge_single_bridge_desc, R.string.cat_hinge_single_bridge_cues,
                    DYNAMIC, UNILATERAL, difficulty = 2,
                    working = Standard(3, 8), moveOn = Standard(3, 15),
                    primaryMuscles = setOf(Muscle.GLUTES), secondaryMuscles = setOf(Muscle.HAMSTRINGS),
                    equipment = emptySet(),
                ),
                CatalogueStep(
                    "hinge.hip_thrust", "hinge", R.string.cat_hinge_hip_thrust, R.string.cat_hinge_hip_thrust_desc, R.string.cat_hinge_hip_thrust_cues,
                    DYNAMIC, UNILATERAL, difficulty = 3,
                    working = Standard(3, 8), moveOn = Standard(3, 15),
                    primaryMuscles = setOf(Muscle.GLUTES), secondaryMuscles = setOf(Muscle.HAMSTRINGS, Muscle.QUADRICEPS),
                    equipment = setOf(Equipment.BENCH),
                ),
                CatalogueStep(
                    "hinge.slider_curl", "hinge", R.string.cat_hinge_slider_curl, R.string.cat_hinge_slider_curl_desc, R.string.cat_hinge_slider_curl_cues,
                    DYNAMIC, BILATERAL, difficulty = 4,
                    working = Standard(3, 6), moveOn = Standard(3, 12),
                    primaryMuscles = setOf(Muscle.HAMSTRINGS), secondaryMuscles = setOf(Muscle.GLUTES),
                    equipment = setOf(Equipment.SLIDER),
                ),
                CatalogueStep(
                    "hinge.nordic_negative", "hinge", R.string.cat_hinge_nordic_negative, R.string.cat_hinge_nordic_negative_desc, R.string.cat_hinge_nordic_negative_cues,
                    DYNAMIC, BILATERAL, difficulty = 6,
                    working = Standard(3, 3), moveOn = Standard(3, 6),
                    primaryMuscles = setOf(Muscle.HAMSTRINGS), secondaryMuscles = setOf(Muscle.GLUTES, Muscle.CALVES),
                    equipment = setOf(Equipment.ANCHOR),
                ),
                CatalogueStep(
                    "hinge.nordic", "hinge", R.string.cat_hinge_nordic, R.string.cat_hinge_nordic_desc, R.string.cat_hinge_nordic_cues,
                    DYNAMIC, BILATERAL, difficulty = 8,
                    working = Standard(3, 2), moveOn = Standard(3, 5),
                    primaryMuscles = setOf(Muscle.HAMSTRINGS), secondaryMuscles = setOf(Muscle.GLUTES, Muscle.CALVES),
                    equipment = setOf(Equipment.ANCHOR),
                ),
            ),
        ),
        CatalogueChain(
            "core", R.string.cat_chain_core, MovementPattern.CORE_ANTI_EXTENSION,
            listOf(
                CatalogueStep(
                    "core.dead_bug", "core", R.string.cat_core_dead_bug, R.string.cat_core_dead_bug_desc, R.string.cat_core_dead_bug_cues,
                    DYNAMIC, BILATERAL, difficulty = 1,
                    working = Standard(3, 8), moveOn = Standard(3, 15),
                    primaryMuscles = setOf(Muscle.ABDOMINALS), secondaryMuscles = emptySet(),
                    equipment = emptySet(),
                ),
                CatalogueStep(
                    "core.plank", "core", R.string.cat_core_plank, R.string.cat_core_plank_desc, R.string.cat_core_plank_cues,
                    ISOMETRIC, BILATERAL, difficulty = 2,
                    working = Standard(3, 20), moveOn = Standard(3, 60),
                    primaryMuscles = setOf(Muscle.ABDOMINALS), secondaryMuscles = setOf(Muscle.SHOULDERS, Muscle.GLUTES),
                    equipment = emptySet(),
                ),
                CatalogueStep(
                    "core.hollow_tuck", "core", R.string.cat_core_hollow_tuck, R.string.cat_core_hollow_tuck_desc, R.string.cat_core_hollow_tuck_cues,
                    ISOMETRIC, BILATERAL, difficulty = 3,
                    working = Standard(3, 15), moveOn = Standard(3, 30),
                    primaryMuscles = setOf(Muscle.ABDOMINALS), secondaryMuscles = emptySet(),
                    equipment = emptySet(),
                ),
                CatalogueStep(
                    "core.hollow", "core", R.string.cat_core_hollow, R.string.cat_core_hollow_desc, R.string.cat_core_hollow_cues,
                    ISOMETRIC, BILATERAL, difficulty = 4,
                    working = Standard(3, 15), moveOn = Standard(3, 40),
                    primaryMuscles = setOf(Muscle.ABDOMINALS), secondaryMuscles = emptySet(),
                    equipment = emptySet(),
                ),
            ),
        ),
        CatalogueChain(
            "leg_raise", R.string.cat_chain_leg_raise, MovementPattern.CORE_FLEXION,
            listOf(
                CatalogueStep(
                    "leg_raise.lying_knee", "leg_raise", R.string.cat_leg_raise_lying_knee, R.string.cat_leg_raise_lying_knee_desc, R.string.cat_leg_raise_lying_knee_cues,
                    DYNAMIC, BILATERAL, difficulty = 1,
                    working = Standard(3, 10), moveOn = Standard(3, 20),
                    primaryMuscles = setOf(Muscle.ABDOMINALS), secondaryMuscles = emptySet(),
                    equipment = emptySet(),
                ),
                CatalogueStep(
                    "leg_raise.lying_leg", "leg_raise", R.string.cat_leg_raise_lying_leg, R.string.cat_leg_raise_lying_leg_desc, R.string.cat_leg_raise_lying_leg_cues,
                    DYNAMIC, BILATERAL, difficulty = 2,
                    working = Standard(3, 8), moveOn = Standard(3, 15),
                    primaryMuscles = setOf(Muscle.ABDOMINALS), secondaryMuscles = emptySet(),
                    equipment = emptySet(),
                ),
                CatalogueStep(
                    "leg_raise.hanging_knee", "leg_raise", R.string.cat_leg_raise_hanging_knee, R.string.cat_leg_raise_hanging_knee_desc, R.string.cat_leg_raise_hanging_knee_cues,
                    DYNAMIC, BILATERAL, difficulty = 4,
                    working = Standard(3, 8), moveOn = Standard(3, 15),
                    primaryMuscles = setOf(Muscle.ABDOMINALS), secondaryMuscles = setOf(Muscle.FOREARMS),
                    equipment = setOf(Equipment.PULL_UP_BAR),
                ),
                CatalogueStep(
                    "leg_raise.hanging_leg", "leg_raise", R.string.cat_leg_raise_hanging_leg, R.string.cat_leg_raise_hanging_leg_desc, R.string.cat_leg_raise_hanging_leg_cues,
                    DYNAMIC, BILATERAL, difficulty = 5,
                    working = Standard(3, 5), moveOn = Standard(3, 12),
                    primaryMuscles = setOf(Muscle.ABDOMINALS), secondaryMuscles = setOf(Muscle.FOREARMS),
                    equipment = setOf(Equipment.PULL_UP_BAR),
                ),
                CatalogueStep(
                    "leg_raise.toes_to_bar", "leg_raise", R.string.cat_leg_raise_toes_to_bar, R.string.cat_leg_raise_toes_to_bar_desc, R.string.cat_leg_raise_toes_to_bar_cues,
                    DYNAMIC, BILATERAL, difficulty = 6,
                    working = Standard(3, 3), moveOn = Standard(3, 10),
                    primaryMuscles = setOf(Muscle.ABDOMINALS), secondaryMuscles = setOf(Muscle.LATS, Muscle.FOREARMS),
                    equipment = setOf(Equipment.PULL_UP_BAR),
                ),
            ),
        ),
        CatalogueChain(
            "handstand", R.string.cat_chain_handstand, MovementPattern.VERTICAL_PUSH,
            listOf(
                CatalogueStep(
                    "handstand.crow", "handstand", R.string.cat_handstand_crow, R.string.cat_handstand_crow_desc, R.string.cat_handstand_crow_cues,
                    ISOMETRIC, BILATERAL, difficulty = 3,
                    working = Standard(3, 10), moveOn = Standard(3, 30),
                    primaryMuscles = setOf(Muscle.SHOULDERS), secondaryMuscles = setOf(Muscle.FOREARMS, Muscle.ABDOMINALS, Muscle.TRICEPS),
                    equipment = emptySet(),
                ),
                CatalogueStep(
                    "handstand.wall_walk", "handstand", R.string.cat_handstand_wall_walk, R.string.cat_handstand_wall_walk_desc, R.string.cat_handstand_wall_walk_cues,
                    DYNAMIC, BILATERAL, difficulty = 4,
                    working = Standard(3, 2), moveOn = Standard(3, 5),
                    primaryMuscles = setOf(Muscle.SHOULDERS), secondaryMuscles = setOf(Muscle.ABDOMINALS, Muscle.TRICEPS),
                    equipment = setOf(Equipment.WALL),
                ),
                CatalogueStep(
                    "handstand.kick_up", "handstand", R.string.cat_handstand_kick_up, R.string.cat_handstand_kick_up_desc, R.string.cat_handstand_kick_up_cues,
                    DYNAMIC, BILATERAL, difficulty = 5,
                    working = Standard(3, 5), moveOn = Standard(3, 10),
                    primaryMuscles = setOf(Muscle.SHOULDERS), secondaryMuscles = setOf(Muscle.ABDOMINALS),
                    equipment = emptySet(), prerequisites = setOf("vpush.wall_hold"),
                ),
                CatalogueStep(
                    "handstand.freestanding", "handstand", R.string.cat_handstand_freestanding, R.string.cat_handstand_freestanding_desc, R.string.cat_handstand_freestanding_cues,
                    ISOMETRIC, BILATERAL, difficulty = 7,
                    working = Standard(3, 10), moveOn = Standard(3, 30),
                    primaryMuscles = setOf(Muscle.SHOULDERS), secondaryMuscles = setOf(Muscle.ABDOMINALS, Muscle.FOREARMS, Muscle.TRAPS),
                    equipment = emptySet(), prerequisites = setOf("vpush.wall_hold"),
                ),
            ),
        ),
        CatalogueChain(
            "l_sit", R.string.cat_chain_l_sit, MovementPattern.CORE_FLEXION,
            listOf(
                CatalogueStep(
                    "l_sit.foot_supported", "l_sit", R.string.cat_l_sit_foot_supported, R.string.cat_l_sit_foot_supported_desc, R.string.cat_l_sit_foot_supported_cues,
                    ISOMETRIC, BILATERAL, difficulty = 2,
                    working = Standard(3, 10), moveOn = Standard(3, 30),
                    primaryMuscles = setOf(Muscle.ABDOMINALS), secondaryMuscles = setOf(Muscle.TRICEPS, Muscle.SHOULDERS),
                    equipment = emptySet(),
                ),
                CatalogueStep(
                    "l_sit.tuck", "l_sit", R.string.cat_l_sit_tuck, R.string.cat_l_sit_tuck_desc, R.string.cat_l_sit_tuck_cues,
                    ISOMETRIC, BILATERAL, difficulty = 4,
                    working = Standard(3, 10), moveOn = Standard(3, 30),
                    primaryMuscles = setOf(Muscle.ABDOMINALS), secondaryMuscles = setOf(Muscle.TRICEPS, Muscle.SHOULDERS),
                    equipment = emptySet(),
                ),
                CatalogueStep(
                    "l_sit.one_leg", "l_sit", R.string.cat_l_sit_one_leg, R.string.cat_l_sit_one_leg_desc, R.string.cat_l_sit_one_leg_cues,
                    ISOMETRIC, BILATERAL, difficulty = 5,
                    working = Standard(3, 10), moveOn = Standard(3, 20),
                    primaryMuscles = setOf(Muscle.ABDOMINALS), secondaryMuscles = setOf(Muscle.QUADRICEPS, Muscle.TRICEPS),
                    equipment = emptySet(),
                ),
                CatalogueStep(
                    "l_sit.full", "l_sit", R.string.cat_l_sit_full, R.string.cat_l_sit_full_desc, R.string.cat_l_sit_full_cues,
                    ISOMETRIC, BILATERAL, difficulty = 6,
                    working = Standard(3, 10), moveOn = Standard(3, 30),
                    primaryMuscles = setOf(Muscle.ABDOMINALS), secondaryMuscles = setOf(Muscle.QUADRICEPS, Muscle.TRICEPS, Muscle.SHOULDERS),
                    equipment = setOf(Equipment.PARALLEL_BARS), prerequisites = setOf("dip.support"),
                ),
                CatalogueStep(
                    "l_sit.v_sit", "l_sit", R.string.cat_l_sit_v_sit, R.string.cat_l_sit_v_sit_desc, R.string.cat_l_sit_v_sit_cues,
                    ISOMETRIC, BILATERAL, difficulty = 9,
                    working = Standard(3, 5), moveOn = Standard(3, 15),
                    primaryMuscles = setOf(Muscle.ABDOMINALS), secondaryMuscles = setOf(Muscle.QUADRICEPS, Muscle.SHOULDERS, Muscle.TRICEPS),
                    equipment = emptySet(),
                ),
            ),
        ),
        CatalogueChain(
            "muscle_up", R.string.cat_chain_muscle_up, MovementPattern.VERTICAL_PULL,
            listOf(
                CatalogueStep(
                    "muscle_up.high_pull", "muscle_up", R.string.cat_muscle_up_high_pull, R.string.cat_muscle_up_high_pull_desc, R.string.cat_muscle_up_high_pull_cues,
                    DYNAMIC, BILATERAL, difficulty = 6,
                    working = Standard(3, 3), moveOn = Standard(3, 8),
                    primaryMuscles = setOf(Muscle.LATS), secondaryMuscles = setOf(Muscle.BICEPS, Muscle.MIDDLE_BACK),
                    equipment = setOf(Equipment.PULL_UP_BAR), prerequisites = setOf("pull.full"),
                ),
                CatalogueStep(
                    "muscle_up.negative", "muscle_up", R.string.cat_muscle_up_negative, R.string.cat_muscle_up_negative_desc, R.string.cat_muscle_up_negative_cues,
                    DYNAMIC, BILATERAL, difficulty = 7,
                    working = Standard(3, 3), moveOn = Standard(3, 6),
                    primaryMuscles = setOf(Muscle.CHEST, Muscle.TRICEPS), secondaryMuscles = setOf(Muscle.LATS, Muscle.SHOULDERS),
                    equipment = setOf(Equipment.PULL_UP_BAR), prerequisites = setOf("dip.full"),
                ),
                CatalogueStep(
                    "muscle_up.band", "muscle_up", R.string.cat_muscle_up_band, R.string.cat_muscle_up_band_desc, R.string.cat_muscle_up_band_cues,
                    DYNAMIC, BILATERAL, difficulty = 7,
                    working = Standard(3, 2), moveOn = Standard(3, 5),
                    primaryMuscles = setOf(Muscle.LATS, Muscle.TRICEPS), secondaryMuscles = setOf(Muscle.CHEST, Muscle.BICEPS),
                    equipment = setOf(Equipment.PULL_UP_BAR, Equipment.RESISTANCE_BAND),
                ),
                CatalogueStep(
                    "muscle_up.full", "muscle_up", R.string.cat_muscle_up_full, R.string.cat_muscle_up_full_desc, R.string.cat_muscle_up_full_cues,
                    DYNAMIC, BILATERAL, difficulty = 8,
                    working = Standard(3, 1), moveOn = Standard(3, 5),
                    primaryMuscles = setOf(Muscle.LATS, Muscle.TRICEPS), secondaryMuscles = setOf(Muscle.CHEST, Muscle.BICEPS, Muscle.SHOULDERS),
                    equipment = setOf(Equipment.PULL_UP_BAR), prerequisites = setOf("pull.full", "dip.full"),
                ),
            ),
        ),
        CatalogueChain(
            "front_lever", R.string.cat_chain_front_lever, MovementPattern.HORIZONTAL_PULL,
            listOf(
                CatalogueStep(
                    "front_lever.tuck", "front_lever", R.string.cat_front_lever_tuck, R.string.cat_front_lever_tuck_desc, R.string.cat_front_lever_tuck_cues,
                    ISOMETRIC, BILATERAL, difficulty = 6,
                    working = Standard(3, 8), moveOn = Standard(3, 20),
                    primaryMuscles = setOf(Muscle.LATS), secondaryMuscles = setOf(Muscle.ABDOMINALS, Muscle.MIDDLE_BACK, Muscle.BICEPS),
                    equipment = setOf(Equipment.PULL_UP_BAR), prerequisites = setOf("pull.full"),
                ),
                CatalogueStep(
                    "front_lever.adv_tuck", "front_lever", R.string.cat_front_lever_adv_tuck, R.string.cat_front_lever_adv_tuck_desc, R.string.cat_front_lever_adv_tuck_cues,
                    ISOMETRIC, BILATERAL, difficulty = 7,
                    working = Standard(3, 8), moveOn = Standard(3, 20),
                    primaryMuscles = setOf(Muscle.LATS), secondaryMuscles = setOf(Muscle.ABDOMINALS, Muscle.MIDDLE_BACK, Muscle.BICEPS),
                    equipment = setOf(Equipment.PULL_UP_BAR),
                ),
                CatalogueStep(
                    "front_lever.one_leg", "front_lever", R.string.cat_front_lever_one_leg, R.string.cat_front_lever_one_leg_desc, R.string.cat_front_lever_one_leg_cues,
                    ISOMETRIC, BILATERAL, difficulty = 8,
                    working = Standard(3, 5), moveOn = Standard(3, 15),
                    primaryMuscles = setOf(Muscle.LATS), secondaryMuscles = setOf(Muscle.ABDOMINALS, Muscle.MIDDLE_BACK),
                    equipment = setOf(Equipment.PULL_UP_BAR),
                ),
                CatalogueStep(
                    "front_lever.straddle", "front_lever", R.string.cat_front_lever_straddle, R.string.cat_front_lever_straddle_desc, R.string.cat_front_lever_straddle_cues,
                    ISOMETRIC, BILATERAL, difficulty = 9,
                    working = Standard(3, 5), moveOn = Standard(3, 15),
                    primaryMuscles = setOf(Muscle.LATS), secondaryMuscles = setOf(Muscle.ABDOMINALS, Muscle.MIDDLE_BACK, Muscle.GLUTES),
                    equipment = setOf(Equipment.PULL_UP_BAR),
                ),
                CatalogueStep(
                    "front_lever.full", "front_lever", R.string.cat_front_lever_full, R.string.cat_front_lever_full_desc, R.string.cat_front_lever_full_cues,
                    ISOMETRIC, BILATERAL, difficulty = 10,
                    working = Standard(3, 3), moveOn = Standard(3, 12),
                    primaryMuscles = setOf(Muscle.LATS), secondaryMuscles = setOf(Muscle.ABDOMINALS, Muscle.MIDDLE_BACK, Muscle.GLUTES),
                    equipment = setOf(Equipment.PULL_UP_BAR),
                ),
            ),
        ),
        CatalogueChain(
            "back_lever", R.string.cat_chain_back_lever, MovementPattern.HORIZONTAL_PULL,
            listOf(
                CatalogueStep(
                    "back_lever.skin_the_cat", "back_lever", R.string.cat_back_lever_skin_the_cat, R.string.cat_back_lever_skin_the_cat_desc, R.string.cat_back_lever_skin_the_cat_cues,
                    DYNAMIC, BILATERAL, difficulty = 4,
                    working = Standard(3, 3), moveOn = Standard(3, 8),
                    primaryMuscles = setOf(Muscle.SHOULDERS), secondaryMuscles = setOf(Muscle.LATS, Muscle.BICEPS, Muscle.ABDOMINALS),
                    equipment = setOf(Equipment.PULL_UP_BAR), prerequisites = setOf("pull.dead_hang"),
                ),
                CatalogueStep(
                    "back_lever.german_hang", "back_lever", R.string.cat_back_lever_german_hang, R.string.cat_back_lever_german_hang_desc, R.string.cat_back_lever_german_hang_cues,
                    ISOMETRIC, BILATERAL, difficulty = 4,
                    working = Standard(3, 10), moveOn = Standard(3, 30),
                    primaryMuscles = setOf(Muscle.SHOULDERS), secondaryMuscles = setOf(Muscle.CHEST, Muscle.BICEPS),
                    equipment = setOf(Equipment.PULL_UP_BAR),
                ),
                CatalogueStep(
                    "back_lever.tuck", "back_lever", R.string.cat_back_lever_tuck, R.string.cat_back_lever_tuck_desc, R.string.cat_back_lever_tuck_cues,
                    ISOMETRIC, BILATERAL, difficulty = 5,
                    working = Standard(3, 8), moveOn = Standard(3, 20),
                    primaryMuscles = setOf(Muscle.SHOULDERS), secondaryMuscles = setOf(Muscle.LATS, Muscle.LOWER_BACK, Muscle.BICEPS),
                    equipment = setOf(Equipment.PULL_UP_BAR), prerequisites = setOf("back_lever.skin_the_cat"),
                ),
                CatalogueStep(
                    "back_lever.adv_tuck", "back_lever", R.string.cat_back_lever_adv_tuck, R.string.cat_back_lever_adv_tuck_desc, R.string.cat_back_lever_adv_tuck_cues,
                    ISOMETRIC, BILATERAL, difficulty = 6,
                    working = Standard(3, 8), moveOn = Standard(3, 20),
                    primaryMuscles = setOf(Muscle.SHOULDERS), secondaryMuscles = setOf(Muscle.LATS, Muscle.LOWER_BACK, Muscle.BICEPS),
                    equipment = setOf(Equipment.PULL_UP_BAR),
                ),
                CatalogueStep(
                    "back_lever.straddle", "back_lever", R.string.cat_back_lever_straddle, R.string.cat_back_lever_straddle_desc, R.string.cat_back_lever_straddle_cues,
                    ISOMETRIC, BILATERAL, difficulty = 8,
                    working = Standard(3, 5), moveOn = Standard(3, 15),
                    primaryMuscles = setOf(Muscle.SHOULDERS), secondaryMuscles = setOf(Muscle.LATS, Muscle.LOWER_BACK, Muscle.GLUTES),
                    equipment = setOf(Equipment.PULL_UP_BAR),
                ),
                CatalogueStep(
                    "back_lever.full", "back_lever", R.string.cat_back_lever_full, R.string.cat_back_lever_full_desc, R.string.cat_back_lever_full_cues,
                    ISOMETRIC, BILATERAL, difficulty = 9,
                    working = Standard(3, 5), moveOn = Standard(3, 15),
                    primaryMuscles = setOf(Muscle.SHOULDERS), secondaryMuscles = setOf(Muscle.LATS, Muscle.LOWER_BACK, Muscle.GLUTES),
                    equipment = setOf(Equipment.PULL_UP_BAR),
                ),
            ),
        ),
        CatalogueChain(
            "planche", R.string.cat_chain_planche, MovementPattern.HORIZONTAL_PUSH,
            listOf(
                CatalogueStep(
                    "planche.lean", "planche", R.string.cat_planche_lean, R.string.cat_planche_lean_desc, R.string.cat_planche_lean_cues,
                    ISOMETRIC, BILATERAL, difficulty = 4,
                    working = Standard(3, 10), moveOn = Standard(3, 30),
                    primaryMuscles = setOf(Muscle.SHOULDERS), secondaryMuscles = setOf(Muscle.CHEST, Muscle.ABDOMINALS, Muscle.FOREARMS),
                    equipment = emptySet(), prerequisites = setOf("push.full"),
                ),
                CatalogueStep(
                    "planche.tuck", "planche", R.string.cat_planche_tuck, R.string.cat_planche_tuck_desc, R.string.cat_planche_tuck_cues,
                    ISOMETRIC, BILATERAL, difficulty = 7,
                    working = Standard(3, 5), moveOn = Standard(3, 15),
                    primaryMuscles = setOf(Muscle.SHOULDERS), secondaryMuscles = setOf(Muscle.CHEST, Muscle.ABDOMINALS, Muscle.TRICEPS),
                    equipment = emptySet(), prerequisites = setOf("planche.lean", "dip.full"),
                ),
                CatalogueStep(
                    "planche.adv_tuck", "planche", R.string.cat_planche_adv_tuck, R.string.cat_planche_adv_tuck_desc, R.string.cat_planche_adv_tuck_cues,
                    ISOMETRIC, BILATERAL, difficulty = 8,
                    working = Standard(3, 5), moveOn = Standard(3, 15),
                    primaryMuscles = setOf(Muscle.SHOULDERS), secondaryMuscles = setOf(Muscle.CHEST, Muscle.ABDOMINALS, Muscle.TRICEPS),
                    equipment = emptySet(),
                ),
                CatalogueStep(
                    "planche.straddle", "planche", R.string.cat_planche_straddle, R.string.cat_planche_straddle_desc, R.string.cat_planche_straddle_cues,
                    ISOMETRIC, BILATERAL, difficulty = 9,
                    working = Standard(3, 3), moveOn = Standard(3, 10),
                    primaryMuscles = setOf(Muscle.SHOULDERS), secondaryMuscles = setOf(Muscle.CHEST, Muscle.ABDOMINALS, Muscle.GLUTES),
                    equipment = emptySet(),
                ),
                CatalogueStep(
                    "planche.full", "planche", R.string.cat_planche_full, R.string.cat_planche_full_desc, R.string.cat_planche_full_cues,
                    ISOMETRIC, BILATERAL, difficulty = 10,
                    working = Standard(3, 3), moveOn = Standard(3, 8),
                    primaryMuscles = setOf(Muscle.SHOULDERS), secondaryMuscles = setOf(Muscle.CHEST, Muscle.ABDOMINALS, Muscle.GLUTES),
                    equipment = emptySet(),
                ),
            ),
        ),
        CatalogueChain(
            "side", R.string.cat_chain_side, MovementPattern.CORE_LATERAL,
            listOf(
                CatalogueStep(
                    "side.knee_plank", "side", R.string.cat_side_knee_plank, R.string.cat_side_knee_plank_desc, R.string.cat_side_knee_plank_cues,
                    ISOMETRIC, UNILATERAL, difficulty = 1,
                    working = Standard(3, 15), moveOn = Standard(3, 30),
                    primaryMuscles = setOf(Muscle.ABDOMINALS), secondaryMuscles = setOf(Muscle.SHOULDERS, Muscle.GLUTES),
                    equipment = emptySet(),
                ),
                CatalogueStep(
                    "side.plank", "side", R.string.cat_side_plank, R.string.cat_side_plank_desc, R.string.cat_side_plank_cues,
                    ISOMETRIC, UNILATERAL, difficulty = 2,
                    working = Standard(3, 20), moveOn = Standard(3, 45),
                    primaryMuscles = setOf(Muscle.ABDOMINALS), secondaryMuscles = setOf(Muscle.SHOULDERS, Muscle.GLUTES),
                    equipment = emptySet(),
                ),
                CatalogueStep(
                    "side.hip_lift", "side", R.string.cat_side_hip_lift, R.string.cat_side_hip_lift_desc, R.string.cat_side_hip_lift_cues,
                    DYNAMIC, UNILATERAL, difficulty = 3,
                    working = Standard(3, 8), moveOn = Standard(3, 15),
                    primaryMuscles = setOf(Muscle.ABDOMINALS), secondaryMuscles = setOf(Muscle.SHOULDERS, Muscle.GLUTES),
                    equipment = emptySet(),
                ),
                CatalogueStep(
                    "side.star", "side", R.string.cat_side_star, R.string.cat_side_star_desc, R.string.cat_side_star_cues,
                    ISOMETRIC, UNILATERAL, difficulty = 4,
                    working = Standard(3, 10), moveOn = Standard(3, 30),
                    primaryMuscles = setOf(Muscle.ABDOMINALS), secondaryMuscles = setOf(Muscle.SHOULDERS, Muscle.GLUTES, Muscle.ABDUCTORS),
                    equipment = emptySet(),
                ),
            ),
        ),
        CatalogueChain(
            "human_flag", R.string.cat_chain_human_flag, MovementPattern.CORE_LATERAL,
            listOf(
                CatalogueStep(
                    "human_flag.vertical", "human_flag", R.string.cat_human_flag_vertical, R.string.cat_human_flag_vertical_desc, R.string.cat_human_flag_vertical_cues,
                    ISOMETRIC, UNILATERAL, difficulty = 6,
                    working = Standard(3, 5), moveOn = Standard(3, 15),
                    primaryMuscles = setOf(Muscle.LATS), secondaryMuscles = setOf(Muscle.SHOULDERS, Muscle.ABDOMINALS, Muscle.FOREARMS),
                    equipment = setOf(Equipment.POLE), prerequisites = setOf("side.star", "pull.full"),
                ),
                CatalogueStep(
                    "human_flag.tuck", "human_flag", R.string.cat_human_flag_tuck, R.string.cat_human_flag_tuck_desc, R.string.cat_human_flag_tuck_cues,
                    ISOMETRIC, UNILATERAL, difficulty = 7,
                    working = Standard(3, 5), moveOn = Standard(3, 15),
                    primaryMuscles = setOf(Muscle.LATS), secondaryMuscles = setOf(Muscle.SHOULDERS, Muscle.ABDOMINALS, Muscle.FOREARMS),
                    equipment = setOf(Equipment.POLE),
                ),
                CatalogueStep(
                    "human_flag.one_leg", "human_flag", R.string.cat_human_flag_one_leg, R.string.cat_human_flag_one_leg_desc, R.string.cat_human_flag_one_leg_cues,
                    ISOMETRIC, UNILATERAL, difficulty = 8,
                    working = Standard(3, 5), moveOn = Standard(3, 15),
                    primaryMuscles = setOf(Muscle.LATS), secondaryMuscles = setOf(Muscle.SHOULDERS, Muscle.ABDOMINALS, Muscle.GLUTES),
                    equipment = setOf(Equipment.POLE),
                ),
                CatalogueStep(
                    "human_flag.straddle", "human_flag", R.string.cat_human_flag_straddle, R.string.cat_human_flag_straddle_desc, R.string.cat_human_flag_straddle_cues,
                    ISOMETRIC, UNILATERAL, difficulty = 9,
                    working = Standard(3, 3), moveOn = Standard(3, 10),
                    primaryMuscles = setOf(Muscle.LATS), secondaryMuscles = setOf(Muscle.SHOULDERS, Muscle.ABDOMINALS, Muscle.GLUTES),
                    equipment = setOf(Equipment.POLE),
                ),
                CatalogueStep(
                    "human_flag.full", "human_flag", R.string.cat_human_flag_full, R.string.cat_human_flag_full_desc, R.string.cat_human_flag_full_cues,
                    ISOMETRIC, UNILATERAL, difficulty = 10,
                    working = Standard(3, 3), moveOn = Standard(3, 8),
                    primaryMuscles = setOf(Muscle.LATS), secondaryMuscles = setOf(Muscle.SHOULDERS, Muscle.ABDOMINALS, Muscle.GLUTES),
                    equipment = setOf(Equipment.POLE),
                ),
            ),
        ),
    )

    private val stepsById: Map<String, CatalogueStep> = chains.flatMap { it.steps }.associateBy { it.id }
    private val chainsById: Map<String, CatalogueChain> = chains.associateBy { it.id }

    val steps: Collection<CatalogueStep> get() = stepsById.values

    fun step(id: String): CatalogueStep? = stepsById[id]

    fun chain(id: String): CatalogueChain? = chainsById[id]
}
