"""The catalogue: the core chains (v1) and the skill chains (phase 6), the single source for the
generated Kotlin catalogue and its strings.

Every name, description, cue and standard here is written for this project (ADR 0006). Names and
muscle groups are facts; free-exercise-db was used only as a checklist.
"""

D, I = "DYNAMIC", "ISOMETRIC"
B, U = "BILATERAL", "UNILATERAL"

# chain id, name, pattern, steps
# step: (local id, name, kind, laterality, difficulty, working (sets, value), move-on (sets, value),
#        primary muscles, secondary muscles, equipment, description, cues, prerequisites)
CHAINS = [
    ("push", "Push-up", "HORIZONTAL_PUSH", [
        ("wall", "Wall push-up", D, B, 1, (3, 10), (3, 20), ["chest"], ["shoulders", "triceps"], [],
         "Push away from a wall with your body straight. The easiest way to learn the push-up shape.",
         ["Hands at chest height, a little wider than your shoulders", "Body in one line from head to heels", "Bring your chest to the wall, then press away"], []),
        ("incline", "Incline push-up", D, B, 2, (3, 8), (3, 15), ["chest"], ["shoulders", "triceps"], ["BENCH"],
         "A push-up with your hands on a bench, table or step. The higher the support, the easier it is.",
         ["Hands on the edge, under your shoulders", "Squeeze your glutes to keep your hips level", "Lower until your chest touches the edge"], []),
        ("knee", "Knee push-up", D, B, 2, (3, 8), (3, 15), ["chest"], ["shoulders", "triceps"], [],
         "A push-up from your knees, keeping a straight line from knees to head.",
         ["Knees on a soft surface, hips forward", "Elbows about 45 degrees from your body", "Lower your chest, not your hips"], []),
        ("full", "Push-up", D, B, 3, (3, 5), (3, 12), ["chest"], ["shoulders", "triceps", "abdominals"], [],
         "The classic push-up: hands and toes on the floor, body straight, chest down to a fist's height.",
         ["Hands under your shoulders, fingers spread", "Brace your stomach so your back stays flat", "Elbows back at about 45 degrees, not flared out"], []),
        ("diamond", "Diamond push-up", D, B, 4, (3, 5), (3, 10), ["triceps"], ["chest", "shoulders"], [],
         "A push-up with your hands close together under your chest, which shifts the work to your triceps.",
         ["Thumbs and index fingers touching under your chest", "Keep elbows close to your sides", "Lower until your chest meets your hands"], []),
        ("decline", "Decline push-up", D, B, 4, (3, 5), (3, 10), ["chest", "shoulders"], ["triceps"], ["BENCH"],
         "A push-up with your feet raised on a bench or step, putting more of your weight on your arms.",
         ["Feet on the bench, hands on the floor", "Keep your hips in line, not piked up", "Lower your forehead towards the floor between your hands"], []),
        ("archer", "Archer push-up", D, U, 6, (3, 4), (3, 8), ["chest"], ["triceps", "shoulders"], [],
         "A wide push-up where one arm does most of the work while the other stays straight to the side.",
         ["Hands about twice shoulder width", "Bend one arm and keep the other straight", "Shift your chest over the working hand"], []),
        ("one_arm", "One-arm push-up", D, U, 8, (3, 2), (3, 6), ["chest", "triceps"], ["shoulders", "abdominals"], [],
         "A push-up on one hand with feet wide for balance. A long-term goal of the push chain.",
         ["Feet wide, free hand behind your back", "Working hand under your chest, slightly inward", "Keep your shoulders square to the floor"], []),
    ]),
    ("vpush", "Handstand push-up", "VERTICAL_PUSH", [
        ("pike", "Pike push-up", D, B, 3, (3, 5), (3, 10), ["shoulders"], ["triceps", "chest"], [],
         "A push-up with your hips high, so your body makes an upside-down V and your shoulders do the pressing.",
         ["Walk your feet in until your hips are high", "Lower the top of your head between your hands", "Press back up through your shoulders"], []),
        ("elevated_pike", "Elevated pike push-up", D, B, 4, (3, 5), (3, 10), ["shoulders"], ["triceps"], ["BENCH"],
         "A pike push-up with your feet on a bench, closer to a handstand and harder on your shoulders.",
         ["Feet on the bench, hips straight above your hands", "Lower your head in front of your hands, forming a triangle", "Keep your elbows over your wrists"], []),
        ("wall_hold", "Wall handstand", I, B, 4, (3, 15), (3, 45), ["shoulders"], ["triceps", "abdominals"], ["WALL"],
         "Holding a handstand with your chest facing the wall, building strength and comfort upside down.",
         ["Walk your feet up the wall as your hands come close", "Push the floor away, arms straight", "Ribs in, body in one line"], []),
        ("wall_negative", "Wall handstand push-up negative", D, B, 6, (3, 3), (3, 6), ["shoulders", "triceps"], [], ["WALL"],
         "From a wall handstand, lower yourself slowly to your head, then come down and start again.",
         ["Take three to five seconds to lower", "Head lands in front of your hands", "Use a cushion under your head at first"], []),
        ("wall_hspu", "Wall handstand push-up", D, B, 7, (3, 3), (3, 8), ["shoulders", "triceps"], ["traps"], ["WALL"],
         "A full push-up in a handstand against the wall, lowering to your head and pressing back up.",
         ["Hands shoulder width, a hand's length from the wall", "Lower under control to a cushion", "Press straight up and lock your arms"], []),
    ]),
    ("dip", "Dip", "VERTICAL_PUSH", [
        ("bench", "Bench dip", D, B, 2, (3, 8), (3, 15), ["triceps"], ["chest", "shoulders"], ["BENCH"],
         "Dipping with your hands on a bench behind you and your feet on the floor.",
         ["Hands at the edge, fingers forward", "Keep your back close to the bench", "Lower until your upper arms are level, no further"], []),
        ("support", "Support hold", I, B, 3, (3, 10), (3, 30), ["triceps", "shoulders"], ["chest"], ["PARALLEL_BARS"],
         "Holding yourself up on straight arms on parallel bars, the top of a dip.",
         ["Arms locked straight", "Shoulders pushed down, away from your ears", "Legs together, slightly in front"], []),
        ("negative", "Dip negative", D, B, 4, (3, 3), (3, 6), ["chest", "triceps"], ["shoulders"], ["PARALLEL_BARS"],
         "From the support hold, lowering yourself slowly into the bottom of a dip.",
         ["Take three to five seconds to lower", "Lean slightly forward", "Stop when your shoulders are just below your elbows"], []),
        ("full", "Dip", D, B, 5, (3, 5), (3, 10), ["chest", "triceps"], ["shoulders"], ["PARALLEL_BARS"],
         "Lowering and pressing back up on parallel bars.",
         ["Start from a straight-arm support", "Lower until your shoulders are just below your elbows", "Press up until your arms are straight"], []),
    ]),
    ("pull", "Pull-up", "VERTICAL_PULL", [
        ("dead_hang", "Dead hang", I, B, 1, (3, 15), (3, 45), ["forearms"], ["lats", "shoulders"], ["PULL_UP_BAR"],
         "Hanging from a bar with straight arms, building grip and shoulder strength for pulling.",
         ["Grip a little wider than your shoulders", "Relax your legs, keep your body still", "Breathe steadily"], []),
        ("scapular", "Scapular pull-up", D, B, 2, (3, 6), (3, 12), ["lats", "middle back"], ["traps"], ["PULL_UP_BAR"],
         "From a dead hang, pulling your shoulder blades down and back without bending your arms.",
         ["Arms stay straight", "Lift your chest slightly by pulling your shoulders down", "Lower with control"], []),
        ("negative", "Pull-up negative", D, B, 3, (3, 3), (3, 6), ["lats"], ["biceps", "middle back"], ["PULL_UP_BAR"],
         "Starting with your chin over the bar, lowering yourself slowly to a hang.",
         ["Jump or step up to the top", "Take three to five seconds to lower", "Finish in a full hang"], []),
        ("band", "Band-assisted pull-up", D, B, 3, (3, 5), (3, 10), ["lats"], ["biceps", "middle back"], ["PULL_UP_BAR", "RESISTANCE_BAND"],
         "A pull-up with a resistance band under your knee or foot taking some of your weight.",
         ["Loop the band over the bar, then step into it", "Pull until your chin is over the bar", "Use a lighter band as you get stronger"], []),
        ("chin", "Chin-up", D, B, 4, (3, 4), (3, 8), ["lats", "biceps"], ["middle back"], ["PULL_UP_BAR"],
         "A pull-up with your palms facing you, which gets more help from your biceps.",
         ["Hands shoulder width, palms towards you", "Pull your elbows down to your sides", "Chin over the bar, then lower fully"], []),
        ("full", "Pull-up", D, B, 5, (3, 4), (3, 8), ["lats"], ["biceps", "middle back", "forearms"], ["PULL_UP_BAR"],
         "Pulling yourself up from a dead hang until your chin is over the bar, palms facing away.",
         ["Hands a little wider than your shoulders", "Start each rep from a full hang", "Lead with your chest, not your chin"], []),
        ("archer", "Archer pull-up", D, U, 7, (3, 3), (3, 6), ["lats"], ["biceps", "forearms"], ["PULL_UP_BAR"],
         "A wide pull-up towards one hand while the other arm stays nearly straight.",
         ["Grip wide", "Pull towards one hand, sliding the other arm straight", "Alternate sides each set or each rep"], []),
        ("one_arm_negative", "One-arm pull-up negative", D, U, 8, (3, 2), (3, 4), ["lats", "biceps"], ["forearms"], ["PULL_UP_BAR"],
         "From the top of a pull-up, lowering yourself slowly on one arm.",
         ["Start at the top with both hands, then let one go", "Lower as slowly as you can", "Keep your shoulder pulled down"], []),
        ("one_arm", "One-arm pull-up", D, U, 9, (3, 1), (3, 3), ["lats", "biceps"], ["forearms", "middle back"], ["PULL_UP_BAR"],
         "A full pull-up on one arm. A long-term goal of the pull chain.",
         ["Start from a still hang", "Turn your body slightly towards the working arm", "Pull your elbow down to your side"], []),
    ]),
    ("row", "Row", "HORIZONTAL_PULL", [
        ("incline", "Incline row", D, B, 1, (3, 8), (3, 15), ["middle back", "lats"], ["biceps"], ["LOW_BAR"],
         "Pulling your chest to a high bar or sturdy table edge with your body leaning back at an angle.",
         ["The more upright you stand, the easier it is", "Body straight from head to heels", "Pull your chest to the bar"], []),
        ("horizontal", "Horizontal row", D, B, 3, (3, 5), (3, 12), ["middle back", "lats"], ["biceps", "shoulders"], ["LOW_BAR"],
         "Hanging under a waist-high bar with your body straight and heels on the floor, pulling your chest up to it.",
         ["Bar at about hip height", "Squeeze your shoulder blades together at the top", "Lower until your arms are straight"], []),
        ("feet_elevated", "Feet-elevated row", D, B, 4, (3, 5), (3, 12), ["middle back", "lats"], ["biceps"], ["LOW_BAR", "BENCH"],
         "A horizontal row with your feet on a bench, so your body is level and you lift more of your weight.",
         ["Feet on the bench, body level", "Keep your hips up", "Pull your chest all the way to the bar"], []),
        ("archer", "Archer row", D, U, 6, (3, 4), (3, 8), ["middle back", "lats"], ["biceps"], ["LOW_BAR"],
         "A wide row pulling towards one hand while the other arm stays straight.",
         ["Grip wide", "Pull towards one hand, the other arm stays straight", "Keep your body from twisting"], []),
        ("one_arm", "One-arm row", D, U, 7, (3, 3), (3, 8), ["middle back", "lats"], ["biceps", "abdominals"], ["LOW_BAR"],
         "A horizontal row on one arm, with your feet wide to stop your body turning.",
         ["Feet wide for balance", "Working hand in line with your chest", "Fight the twist as you pull"], []),
    ]),
    ("squat", "Squat", "SQUAT", [
        ("assisted", "Assisted squat", D, B, 1, (3, 10), (3, 20), ["quadriceps"], ["glutes", "hamstrings"], [],
         "A squat holding a door frame or sturdy support, using your arms as little as you need.",
         ["Feet shoulder width, toes slightly out", "Sit back and down as if onto a chair", "Push through your whole foot to stand"], []),
        ("full", "Bodyweight squat", D, B, 2, (3, 10), (3, 25), ["quadriceps"], ["glutes", "hamstrings"], [],
         "A full squat with no support, hips going down to at least knee height.",
         ["Feet shoulder width, toes slightly out", "Knees travel in the direction of your toes", "Chest up, heels down"], []),
        ("split", "Split squat", D, U, 3, (3, 8), (3, 15), ["quadriceps", "glutes"], ["hamstrings"], [],
         "From a long step stance, lowering your back knee towards the floor and standing back up.",
         ["Feet a long stride apart", "Lower straight down, not forward", "Front knee follows your toes"], []),
        ("bulgarian", "Bulgarian split squat", D, U, 4, (3, 6), (3, 12), ["quadriceps", "glutes"], ["hamstrings"], ["BENCH"],
         "A split squat with your back foot raised on a bench, so the front leg works harder.",
         ["Back foot laces-down on the bench", "Front foot far enough forward that your knee stays over it", "Lower until your back knee nearly touches the floor"], []),
        ("assisted_pistol", "Assisted pistol squat", D, U, 5, (3, 5), (3, 10), ["quadriceps", "glutes"], ["hamstrings", "abdominals"], [],
         "A one-leg squat holding a support, with the other leg out in front.",
         ["Hold a door frame or pole", "Free leg straight out in front", "Lower slowly on the standing leg"], []),
        ("shrimp", "Shrimp squat", D, U, 6, (3, 3), (3, 8), ["quadriceps", "glutes"], ["hamstrings"], [],
         "A one-leg squat holding your other foot behind you and lowering your back knee to the floor.",
         ["Hold your rear foot with the hand on the same side", "Lean forward a little for balance", "Touch your knee down softly"], []),
        ("pistol", "Pistol squat", D, U, 7, (3, 3), (3, 8), ["quadriceps", "glutes"], ["hamstrings", "abdominals"], [],
         "A full one-leg squat with the other leg held straight out in front. A goal of the squat chain.",
         ["Arms forward for balance", "Heel stays down the whole way", "Go all the way down, then drive up"], []),
    ]),
    ("hinge", "Hip hinge", "HINGE", [
        ("bridge", "Glute bridge", D, B, 1, (3, 10), (3, 20), ["glutes"], ["hamstrings", "lower back"], [],
         "Lying on your back with knees bent, lifting your hips until your body is straight from knees to shoulders.",
         ["Feet flat, close to your hips", "Push through your heels", "Squeeze your glutes at the top, ribs down"], []),
        ("single_bridge", "Single-leg glute bridge", D, U, 2, (3, 8), (3, 15), ["glutes"], ["hamstrings"], [],
         "A glute bridge on one leg, the other held up straight or bent.",
         ["Working foot close to your hip", "Keep your hips level as you lift", "Pause for a second at the top"], []),
        ("hip_thrust", "Single-leg hip thrust", D, U, 3, (3, 8), (3, 15), ["glutes"], ["hamstrings", "quadriceps"], ["BENCH"],
         "A single-leg bridge with your shoulders on a bench, for a bigger range of motion.",
         ["Shoulder blades on the bench edge", "Chin tucked, eyes forward", "Drive up until your body is level"], []),
        ("slider_curl", "Sliding leg curl", D, B, 4, (3, 6), (3, 12), ["hamstrings"], ["glutes"], ["SLIDER"],
         "From a bridge with your heels on a towel or sliders, pulling your heels in and pushing them out again.",
         ["Hold the bridge the whole time", "Pull your heels towards you", "Slide out slowly"], []),
        ("nordic_negative", "Nordic curl negative", D, B, 6, (3, 3), (3, 6), ["hamstrings"], ["glutes", "calves"], ["ANCHOR"],
         "Kneeling with your ankles held down, lowering your body forward as slowly as you can.",
         ["Ankles anchored under something sturdy", "Body straight from knees to head", "Catch yourself with your hands, push back up"], []),
        ("nordic", "Nordic curl", D, B, 8, (3, 2), (3, 5), ["hamstrings"], ["glutes", "calves"], ["ANCHOR"],
         "Lowering forward from your knees and pulling yourself back up with your hamstrings alone.",
         ["Ankles anchored", "Hips stay straight, no bending", "Lower and rise under full control"], []),
    ]),
    ("core", "Core", "CORE_ANTI_EXTENSION", [
        ("dead_bug", "Dead bug", D, B, 1, (3, 8), (3, 15), ["abdominals"], [], [],
         "Lying on your back with arms and knees up, lowering opposite arm and leg while keeping your back flat.",
         ["Press your lower back into the floor", "Move slowly, breathe out as you reach", "Alternate sides"], []),
        ("plank", "Plank", I, B, 2, (3, 20), (3, 60), ["abdominals"], ["shoulders", "glutes"], [],
         "Holding a straight body on your forearms and toes.",
         ["Elbows under your shoulders", "Squeeze your glutes and brace your stomach", "Do not let your hips sag"], []),
        ("hollow_tuck", "Tuck hollow hold", I, B, 3, (3, 15), (3, 30), ["abdominals"], [], [],
         "Lying on your back with knees pulled in and shoulders lifted, lower back pressed down.",
         ["Lower back flat on the floor", "Shoulders off the floor, chin slightly in", "Arms reaching towards your feet"], []),
        ("hollow", "Hollow body hold", I, B, 4, (3, 15), (3, 40), ["abdominals"], [], [],
         "Holding a shallow banana shape on your back: legs straight and low, arms overhead, lower back down.",
         ["Lower back stays pressed to the floor", "Legs together and straight", "Raise your legs if your back lifts"], []),
    ]),
    ("leg_raise", "Leg raise", "CORE_FLEXION", [
        ("lying_knee", "Lying knee raise", D, B, 1, (3, 10), (3, 20), ["abdominals"], [], [],
         "Lying on your back, bringing your knees to your chest and lowering them slowly.",
         ["Hands by your hips", "Curl your hips slightly off the floor at the top", "Lower without letting your back arch"], []),
        ("lying_leg", "Lying leg raise", D, B, 2, (3, 8), (3, 15), ["abdominals"], [], [],
         "Lying on your back, raising straight legs to vertical and lowering them slowly.",
         ["Legs together and straight", "Lower back stays down", "Stop just above the floor"], []),
        ("hanging_knee", "Hanging knee raise", D, B, 4, (3, 8), (3, 15), ["abdominals"], ["forearms"], ["PULL_UP_BAR"],
         "Hanging from a bar and raising your knees towards your chest without swinging.",
         ["Start from a still hang", "Curl your pelvis up at the top", "Lower slowly"], []),
        ("hanging_leg", "Hanging leg raise", D, B, 5, (3, 5), (3, 12), ["abdominals"], ["forearms"], ["PULL_UP_BAR"],
         "Hanging from a bar and raising straight legs to hip height or higher.",
         ["Legs straight and together", "No swinging between reps", "Lift until your legs are level"], []),
        ("toes_to_bar", "Toes to bar", D, B, 6, (3, 3), (3, 10), ["abdominals"], ["lats", "forearms"], ["PULL_UP_BAR"],
         "Hanging from a bar and raising straight legs all the way to touch the bar.",
         ["Press the bar down slightly with straight arms", "Lift your legs and curl your hips", "Lower under control"], []),
    ]),

    # ---- Skills (phase 6). Prerequisites are hints shown as "Builds on", never locks (ADR 0005). ----
    ("handstand", "Handstand", "VERTICAL_PUSH", [
        ("crow", "Crow pose", I, B, 3, (3, 10), (3, 30), ["shoulders"], ["forearms", "abdominals", "triceps"], [],
         "Balancing on your hands with your knees resting on the backs of your upper arms. The first taste of weight on the hands.",
         ["Hands flat, fingers spread, shoulder width", "Knees high on your upper arms", "Lean forward until your feet float"], []),
        ("wall_walk", "Wall walk", D, B, 4, (3, 2), (3, 5), ["shoulders"], ["abdominals", "triceps"], ["WALL"],
         "From a push-up position with your feet at a wall, walking your feet up the wall and your hands in, then back out.",
         ["Small steps with hands and feet", "Keep your arms straight and your body tight", "Walk in only as far as you can control"], []),
        ("kick_up", "Handstand kick-up", D, B, 5, (3, 5), (3, 10), ["shoulders"], ["abdominals"], [],
         "Kicking up towards a handstand on open floor and finding the balance point for a moment, then stepping down.",
         ["Hands shoulder width, eyes between them", "Kick with one leg, follow with the other", "Step down to the side if you go over"], ["vpush.wall_hold"]),
        ("freestanding", "Freestanding handstand", I, B, 7, (3, 10), (3, 30), ["shoulders"], ["abdominals", "forearms", "traps"], [],
         "Balancing upside down on your hands without a wall, body in one straight line.",
         ["Push the floor away, shoulders by your ears", "Squeeze your legs together, toes pointed", "Steer with your fingertips"], ["vpush.wall_hold"]),
    ]),
    ("l_sit", "L-sit", "CORE_FLEXION", [
        ("foot_supported", "Foot-supported L-sit", I, B, 2, (3, 10), (3, 30), ["abdominals"], ["triceps", "shoulders"], [],
         "Sitting with your hands by your hips, pressing down to lift your hips while your heels stay on the floor.",
         ["Hands flat beside your hips", "Push down and lift your hips", "Shoulders down, away from your ears"], []),
        ("tuck", "Tuck L-sit", I, B, 4, (3, 10), (3, 30), ["abdominals"], ["triceps", "shoulders"], [],
         "Holding yourself up on straight arms with your knees pulled into your chest.",
         ["Arms locked straight", "Knees tight to your chest", "Press the floor or handles away"], []),
        ("one_leg", "One-leg L-sit", I, B, 5, (3, 10), (3, 20), ["abdominals"], ["quadriceps", "triceps"], [],
         "A tuck L-sit with one leg straightened out in front, changing legs each set.",
         ["One knee tucked, the other leg straight", "Lift the straight leg level with your hips", "Change legs each set"], []),
        ("full", "L-sit", I, B, 6, (3, 10), (3, 30), ["abdominals"], ["quadriceps", "triceps", "shoulders"], ["PARALLEL_BARS"],
         "Holding yourself up on straight arms with both legs straight out in front, making an L.",
         ["Legs straight and together, level with your hips", "Point your toes", "Keep pushing down through your hands"], ["dip.support"]),
        ("v_sit", "V-sit", I, B, 9, (3, 5), (3, 15), ["abdominals"], ["quadriceps", "shoulders", "triceps"], [],
         "From an L-sit, lifting your straight legs higher until your body makes a V.",
         ["Lean your shoulders back a little", "Lift your legs as high as you can", "Keep your arms straight"], []),
    ]),
    ("muscle_up", "Muscle-up", "VERTICAL_PULL", [
        ("high_pull", "Chest-to-bar pull-up", D, B, 6, (3, 3), (3, 8), ["lats"], ["biceps", "middle back"], ["PULL_UP_BAR"],
         "A pull-up driven hard enough to bring your chest to the bar: the pull a muscle-up needs.",
         ["Start each rep from a full hang", "Pull fast and drive your elbows down", "Touch the bar with your chest"], ["pull.full"]),
        ("negative", "Muscle-up negative", D, B, 7, (3, 3), (3, 6), ["chest", "triceps"], ["lats", "shoulders"], ["PULL_UP_BAR"],
         "From the top of the bar on straight arms, lowering slowly through the dip and the turn to a hang.",
         ["Start on top with straight arms", "Lower through the dip slowly", "Keep the bar close as you turn under it"], ["dip.full"]),
        ("band", "Band-assisted muscle-up", D, B, 7, (3, 2), (3, 5), ["lats", "triceps"], ["chest", "biceps"], ["PULL_UP_BAR", "RESISTANCE_BAND"],
         "A full muscle-up with a band taking some of your weight through the pull and the turn.",
         ["Pull high, towards your chest", "Lean your chest over the bar quickly", "Press up until your arms are straight"], []),
        ("full", "Muscle-up", D, B, 8, (3, 1), (3, 5), ["lats", "triceps"], ["chest", "biceps", "shoulders"], ["PULL_UP_BAR"],
         "Pulling yourself up from a hang and over the bar in one movement, finishing on straight arms above it.",
         ["Pull explosively, the bar to your chest", "Turn your wrists and lean over the bar", "Press to straight arms"], ["pull.full", "dip.full"]),
    ]),
    ("front_lever", "Front lever", "HORIZONTAL_PULL", [
        ("tuck", "Tuck front lever", I, B, 6, (3, 8), (3, 20), ["lats"], ["abdominals", "middle back", "biceps"], ["PULL_UP_BAR"],
         "Hanging from a bar with straight arms, holding your body level with your knees tucked to your chest.",
         ["Arms straight, pull the bar down towards your hips", "Back flat and level with the floor", "Knees tight to your chest"], ["pull.full"]),
        ("adv_tuck", "Advanced tuck front lever", I, B, 7, (3, 8), (3, 20), ["lats"], ["abdominals", "middle back", "biceps"], ["PULL_UP_BAR"],
         "A tuck front lever with your back flat and your hips opened, knees out at a right angle.",
         ["Flatten your back", "Push your knees away until your thighs are level", "Keep pressing the bar down"], []),
        ("one_leg", "One-leg front lever", I, B, 8, (3, 5), (3, 15), ["lats"], ["abdominals", "middle back"], ["PULL_UP_BAR"],
         "A front lever with one leg straight and the other tucked, changing legs each set.",
         ["One leg straight, in line with your body", "The other knee tucked", "Change legs each set"], []),
        ("straddle", "Straddle front lever", I, B, 9, (3, 5), (3, 15), ["lats"], ["abdominals", "middle back", "glutes"], ["PULL_UP_BAR"],
         "A front lever with both legs straight and spread wide, which shortens the lever.",
         ["Legs straight and wide apart", "Hips level with your shoulders", "Squeeze your glutes"], []),
        ("full", "Front lever", I, B, 10, (3, 3), (3, 12), ["lats"], ["abdominals", "middle back", "glutes"], ["PULL_UP_BAR"],
         "Hanging face up with straight arms and your whole body straight and level with the floor.",
         ["Legs together, body in one line", "Pull the bar down with straight arms", "Hold your hips up"], []),
    ]),
    ("back_lever", "Back lever", "HORIZONTAL_PULL", [
        ("skin_the_cat", "Skin the cat", D, B, 4, (3, 3), (3, 8), ["shoulders"], ["lats", "biceps", "abdominals"], ["PULL_UP_BAR"],
         "From a hang, lifting your legs through your arms and rolling over backwards until you hang behind the bar, then returning.",
         ["Tuck your knees and lift them through your arms", "Lower slowly into the stretch behind you", "Come back the same way"], ["pull.dead_hang"]),
        ("german_hang", "German hang", I, B, 4, (3, 10), (3, 30), ["shoulders"], ["chest", "biceps"], ["PULL_UP_BAR"],
         "Hanging from the bar at the bottom of a skin the cat, arms behind you, letting your shoulders open.",
         ["Ease into the stretch slowly", "Keep your arms straight", "Come out the way you went in"], []),
        ("tuck", "Tuck back lever", I, B, 5, (3, 8), (3, 20), ["shoulders"], ["lats", "lower back", "biceps"], ["PULL_UP_BAR"],
         "Hanging face down behind the bar with straight arms, back level, knees tucked to your chest.",
         ["Arms straight, the bar behind your hips", "Back level with the floor", "Knees tight to your chest"], ["back_lever.skin_the_cat"]),
        ("adv_tuck", "Advanced tuck back lever", I, B, 6, (3, 8), (3, 20), ["shoulders"], ["lats", "lower back", "biceps"], ["PULL_UP_BAR"],
         "A tuck back lever with your back flat and your hips opened, knees out at a right angle.",
         ["Flatten your back", "Push your knees away until your thighs are level", "Arms stay straight"], []),
        ("straddle", "Straddle back lever", I, B, 8, (3, 5), (3, 15), ["shoulders"], ["lats", "lower back", "glutes"], ["PULL_UP_BAR"],
         "A back lever with both legs straight and spread wide.",
         ["Legs straight and wide apart", "Body level, face down", "Squeeze your glutes"], []),
        ("full", "Back lever", I, B, 9, (3, 5), (3, 15), ["shoulders"], ["lats", "lower back", "glutes"], ["PULL_UP_BAR"],
         "Hanging face down behind the bar with your whole body straight and level with the floor.",
         ["Legs together, body in one line", "Arms straight, the bar at your hips", "Do not let your hips sag"], []),
    ]),
    ("planche", "Planche", "HORIZONTAL_PUSH", [
        ("lean", "Planche lean", I, B, 4, (3, 10), (3, 30), ["shoulders"], ["chest", "abdominals", "forearms"], [],
         "From the top of a push-up, leaning your shoulders forward past your hands and holding.",
         ["Fingers turned out a little", "Lean forward with straight arms", "Round your upper back slightly"], ["push.full"]),
        ("tuck", "Tuck planche", I, B, 7, (3, 5), (3, 15), ["shoulders"], ["chest", "abdominals", "triceps"], [],
         "Balancing on straight arms with your feet off the floor and your knees tucked under your body.",
         ["Arms locked straight", "Lean forward until your feet lift", "Knees tucked, hips high"], ["planche.lean", "dip.full"]),
        ("adv_tuck", "Advanced tuck planche", I, B, 8, (3, 5), (3, 15), ["shoulders"], ["chest", "abdominals", "triceps"], [],
         "A tuck planche with your back flat and your hips level with your shoulders.",
         ["Flatten your back", "Hips level with your shoulders", "Push the floor away"], []),
        ("straddle", "Straddle planche", I, B, 9, (3, 3), (3, 10), ["shoulders"], ["chest", "abdominals", "glutes"], [],
         "Balancing on straight arms with your body level and your legs straight and spread wide.",
         ["Legs straight and wide apart", "Body level with the floor", "Lean until you balance over your hands"], []),
        ("full", "Planche", I, B, 10, (3, 3), (3, 8), ["shoulders"], ["chest", "abdominals", "glutes"], [],
         "Balancing on straight arms with your whole body straight and level above the floor.",
         ["Legs together, body in one line", "Arms straight, shoulders forward of your hands", "Squeeze everything"], []),
    ]),
]
