"""Generates Catalogue.kt and res/values/catalogue_strings.xml from catalogue_spec.py.

Edit catalogue_spec.py, then run from the repository root:

    python3 scripts/catalogue/generate_catalogue.py .
"""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from catalogue_spec import CHAINS

root = sys.argv[1]
kt = os.path.join(root, "app/src/main/java/io/github/gonbei774/calisthenicsmemory/data/catalogue/Catalogue.kt")
xml = os.path.join(root, "app/src/main/res/values/catalogue_strings.xml")


def key(step_id):
    return "cat_" + step_id.replace(".", "_")


def esc(s):
    return s.replace("&", "&amp;").replace("<", "&lt;").replace("'", "\\'").replace('"', '\\"')


def muscles(ms):
    return "setOf(" + ", ".join("Muscle." + m.upper().replace(" ", "_") for m in ms) + ")" if ms else "emptySet()"


def equipment(es):
    return "setOf(" + ", ".join("Equipment." + e for e in es) + ")" if es else "emptySet()"


out = ['''package io.github.gonbei774.calisthenicsmemory.data.catalogue

import io.github.gonbei774.calisthenicsmemory.R
import io.github.gonbei774.calisthenicsmemory.data.v2.ExerciseKind.DYNAMIC
import io.github.gonbei774.calisthenicsmemory.data.v2.ExerciseKind.ISOMETRIC
import io.github.gonbei774.calisthenicsmemory.data.v2.Laterality.BILATERAL
import io.github.gonbei774.calisthenicsmemory.data.v2.Laterality.UNILATERAL

/**
 * Catalogue v1: the core chains (ADR 0006). Names, descriptions, cues and standards are written
 * for this project; see docs/wiki/Credits.md. Text lives in res/values/catalogue_strings.xml.
 * CatalogueTest checks the rules every entry must follow.
 *
 * Generated by scripts/catalogue/generate_catalogue.py from catalogue_spec.py: edit the spec,
 * then regenerate, rather than editing this file.
 */
object Catalogue {
    val chains: List<CatalogueChain> = listOf(''']
strings = []
for chain_id, chain_name, pattern, steps in CHAINS:
    strings.append(f'    <string name="cat_chain_{chain_id}">{esc(chain_name)}</string>')
    out.append(f'        CatalogueChain(\n            "{chain_id}", R.string.cat_chain_{chain_id}, MovementPattern.{pattern},\n            listOf(')
    for (local, name, kind, lat, diff, working, move_on, prim, sec, eq, desc, cues, prereq) in steps:
        sid = f"{chain_id}.{local}"
        k = key(sid)
        strings.append(f'    <string name="{k}">{esc(name)}</string>')
        strings.append(f'    <string name="{k}_desc">{esc(desc)}</string>')
        strings.append(f'    <string name="{k}_cues">{esc(chr(10).join(cues)).replace(chr(10), chr(92) + "n")}</string>')
        pre = ("setOf(" + ", ".join(f'"{p}"' for p in prereq) + ")") if prereq else None
        lines = [
            f'                CatalogueStep(',
            f'                    "{sid}", "{chain_id}", R.string.{k}, R.string.{k}_desc, R.string.{k}_cues,',
            f'                    {"DYNAMIC" if kind == "DYNAMIC" else "ISOMETRIC"}, {"BILATERAL" if lat == "BILATERAL" else "UNILATERAL"}, difficulty = {diff},',
            f'                    working = Standard({working[0]}, {working[1]}), moveOn = Standard({move_on[0]}, {move_on[1]}),',
            f'                    primaryMuscles = {muscles(prim)}, secondaryMuscles = {muscles(sec)},',
            f'                    equipment = {equipment(eq)},' + (f' prerequisites = {pre},' if pre else ''),
            f'                ),',
        ]
        out.extend(lines)
    out.append('            ),\n        ),')
out.append('''    )

    private val stepsById: Map<String, CatalogueStep> = chains.flatMap { it.steps }.associateBy { it.id }
    private val chainsById: Map<String, CatalogueChain> = chains.associateBy { it.id }

    val steps: Collection<CatalogueStep> get() = stepsById.values

    fun step(id: String): CatalogueStep? = stepsById[id]

    fun chain(id: String): CatalogueChain? = chainsById[id]
}
''')
open(kt, "w").write("\n".join(out))
open(xml, "w").write('''<?xml version="1.0" encoding="utf-8"?>
<!--
    The built-in exercise catalogue (ADR 0006), written for this project. Each step has a name, a
    description (_desc) and form cues, one per line (_cues). Generated with Catalogue.kt by scripts/catalogue/generate_catalogue.py.
    Translations are written by hand in res/values-*/catalogue_strings.xml. When an entry here is
    added or changed, update every translation too; CatalogueTranslationTest checks they match.
-->
<resources>
''' + "\n".join(strings) + "\n</resources>\n")
print("steps", sum(len(c[3]) for c in CHAINS), "strings", len(strings))
