"""Generates BodyMapData.kt from the react-body-highlighter body outlines (MIT).

Usage:
    curl -sSL -o /tmp/rbh.tgz https://registry.npmjs.org/react-body-highlighter/-/react-body-highlighter-2.0.5.tgz
    # sha256: c15467a8fcf48193896ecbaef1eb98ff260e50021cea3454313ff1016f59e2cb
    tar xzf /tmp/rbh.tgz -C /tmp
    python3 scripts/musclemap/generate_body_map.py /tmp/package/src/assets/index.ts .

Only the polygon outlines are used. Their region names are mapped to our own BodyRegion names.
"""
import re
import sys

source, root = sys.argv[1], sys.argv[2]
out = root + "/app/src/main/java/io/github/gonbei774/calisthenicsmemory/ui/components/muscles/BodyMapData.kt"

# Upstream region name -> our BodyRegion. Upstream "ABDUCTOR" is its adductor region.
REGIONS = {
    "CHEST": "CHEST", "OBLIQUES": "OBLIQUES", "ABS": "ABS", "BICEPS": "BICEPS", "TRICEPS": "TRICEPS",
    "NECK": "NECK", "FRONT_DELTOIDS": "FRONT_DELTOIDS", "HEAD": "HEAD", "ABDUCTORS": "ABDUCTORS",
    "QUADRICEPS": "QUADRICEPS", "KNEES": "KNEES", "CALVES": "CALVES", "FOREARM": "FOREARMS",
    "TRAPEZIUS": "TRAPEZIUS", "BACK_DELTOIDS": "BACK_DELTOIDS", "UPPER_BACK": "UPPER_BACK",
    "LOWER_BACK": "LOWER_BACK", "GLUTEAL": "GLUTES", "ABDUCTOR": "ADDUCTORS", "HAMSTRING": "HAMSTRINGS",
    "LEFT_SOLEUS": "SOLEUS", "RIGHT_SOLEUS": "SOLEUS",
}

text = open(source).read()
front_src, back_src = text.split("export const posteriorData")


def shapes(src):
    result = []
    for m in re.finditer(r"muscle:\s*MuscleType\.([A-Z_]+),\s*svgPoints:\s*\[(.*?)\]", src, re.S):
        for poly in re.findall(r"'([^']*)'", m.group(2)):
            values = [round(float(v), 2) for v in poly.split()]
            assert len(values) % 2 == 0 and len(values) >= 6, m.group(1)
            result.append((REGIONS[m.group(1)], values))
    return result


def kotlin(name, items):
    lines = [f"    val {name}: List<BodyShape> = listOf("]
    for region, values in items:
        floats = ", ".join(f"{v:g}f" for v in values)
        lines.append(f"        BodyShape(BodyRegion.{region}, floatArrayOf({floats})),")
    lines.append("    )")
    return "\n".join(lines)


regions = sorted(set(REGIONS.values()))
front, back = shapes(front_src), shapes(back_src)
# The upstream viewBox is 100 by 200, but a few points fall just outside it; size the box to fit them.
xs = [v for _, values in front + back for v in values[0::2]]
ys = [v for _, values in front + back for v in values[1::2]]
assert min(xs) >= 0 and min(ys) >= 0
width, height = max(100, -(-max(xs) // 1)), max(200, -(-max(ys) // 1))
open(out, "w").write(f"""package io.github.gonbei774.calisthenicsmemory.ui.components.muscles

// Generated by scripts/musclemap/generate_body_map.py. Do not edit by hand.
//
// Body outlines adapted from react-body-highlighter 2.0.5
// (https://github.com/GV79/react-body-highlighter), used under the MIT License:
//
// Copyright (c) 2020 GV79
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

/** Areas of the drawn body; [muscleRegions] maps the catalogue's muscles onto them. */
internal enum class BodyRegion {{
    {", ".join(regions)},
}}

/** One closed outline: x, y pairs in a {width:g} by {height:g} box. */
internal class BodyShape(val region: BodyRegion, val points: FloatArray)

internal object BodyMapData {{
    const val WIDTH = {width:g}f
    const val HEIGHT = {height:g}f

{kotlin("front", front)}

{kotlin("back", back)}
}}
""")
print("written", out)
