package io.github.gonbei774.calisthenicsmemory.ui.components.muscles

// Generated by scripts/musclemap/generate_body_map.py. Do not edit by hand.
//
// Body outlines adapted from react-body-highlighter 2.0.5
// (https://github.com/GV79/react-body-highlighter), used under the MIT License:
//
// Copyright (c) 2020 GV79
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

/** Areas of the drawn body; [muscleRegions] maps the catalogue's muscles onto them. */
internal enum class BodyRegion {
    ABDUCTORS, ABS, ADDUCTORS, BACK_DELTOIDS, BICEPS, CALVES, CHEST, FOREARMS, FRONT_DELTOIDS, GLUTES, HAMSTRINGS, HEAD, KNEES, LOWER_BACK, NECK, OBLIQUES, QUADRICEPS, SOLEUS, TRAPEZIUS, TRICEPS, UPPER_BACK,
}

/** One closed outline: x, y pairs in a 100 by 220 box. */
internal class BodyShape(val region: BodyRegion, val points: FloatArray)

internal object BodyMapData {
    const val WIDTH = 100f
    const val HEIGHT = 220f

    val front: List<BodyShape> = listOf(
        BodyShape(BodyRegion.CHEST, floatArrayOf(51.84f, 41.63f, 51.02f, 55.1f, 57.96f, 57.96f, 67.76f, 55.51f, 70.61f, 47.35f, 62.04f, 41.63f)),
        BodyShape(BodyRegion.CHEST, floatArrayOf(29.8f, 46.53f, 31.43f, 55.51f, 40.82f, 57.96f, 48.16f, 55.1f, 47.76f, 42.04f, 37.55f, 42.04f)),
        BodyShape(BodyRegion.OBLIQUES, floatArrayOf(68.57f, 63.27f, 67.35f, 57.14f, 58.78f, 59.59f, 60f, 64.08f, 60.41f, 83.27f, 65.71f, 78.78f, 66.53f, 69.8f)),
        BodyShape(BodyRegion.OBLIQUES, floatArrayOf(33.88f, 78.37f, 33.06f, 71.84f, 31.02f, 63.27f, 32.24f, 57.14f, 40.82f, 59.18f, 39.18f, 63.27f, 39.18f, 83.67f)),
        BodyShape(BodyRegion.ABS, floatArrayOf(56.33f, 59.18f, 57.96f, 64.08f, 58.37f, 77.96f, 58.37f, 92.65f, 56.33f, 98.37f, 55.1f, 104.08f, 51.43f, 107.76f, 51.02f, 84.49f, 50.61f, 67.35f, 51.02f, 57.14f)),
        BodyShape(BodyRegion.ABS, floatArrayOf(43.67f, 58.78f, 48.57f, 57.14f, 48.98f, 67.35f, 48.57f, 84.49f, 48.16f, 107.35f, 44.49f, 103.67f, 40.82f, 91.43f, 40.82f, 78.37f, 41.22f, 64.49f)),
        BodyShape(BodyRegion.BICEPS, floatArrayOf(16.73f, 68.16f, 17.96f, 71.43f, 22.86f, 66.12f, 28.98f, 53.88f, 27.76f, 49.39f, 20.41f, 55.92f)),
        BodyShape(BodyRegion.BICEPS, floatArrayOf(71.43f, 49.39f, 70.2f, 54.69f, 76.33f, 66.12f, 81.63f, 71.84f, 82.86f, 68.98f, 78.78f, 55.51f)),
        BodyShape(BodyRegion.TRICEPS, floatArrayOf(69.39f, 55.51f, 69.39f, 61.63f, 75.92f, 72.65f, 77.55f, 70.2f, 75.51f, 67.35f)),
        BodyShape(BodyRegion.TRICEPS, floatArrayOf(22.45f, 69.39f, 29.8f, 55.51f, 29.8f, 60.82f, 22.86f, 73.06f)),
        BodyShape(BodyRegion.NECK, floatArrayOf(55.51f, 23.67f, 50.61f, 33.47f, 50.61f, 39.18f, 61.63f, 40f, 70.61f, 44.9f, 69.39f, 36.73f, 63.27f, 35.1f, 58.37f, 30.61f)),
        BodyShape(BodyRegion.NECK, floatArrayOf(28.98f, 44.9f, 30.2f, 37.14f, 36.33f, 35.1f, 41.22f, 30.2f, 44.49f, 24.49f, 48.98f, 33.88f, 48.57f, 39.18f, 37.96f, 39.59f)),
        BodyShape(BodyRegion.FRONT_DELTOIDS, floatArrayOf(78.37f, 53.06f, 79.59f, 47.76f, 79.18f, 41.22f, 75.92f, 37.96f, 71.02f, 36.33f, 72.24f, 42.86f, 71.43f, 47.35f)),
        BodyShape(BodyRegion.FRONT_DELTOIDS, floatArrayOf(28.16f, 47.35f, 21.22f, 53.06f, 20f, 47.76f, 20.41f, 40.82f, 24.49f, 37.14f, 28.57f, 37.14f, 26.94f, 43.27f)),
        BodyShape(BodyRegion.HEAD, floatArrayOf(42.45f, 2.86f, 40f, 11.84f, 42.04f, 19.59f, 46.12f, 23.27f, 49.8f, 25.31f, 54.69f, 22.45f, 57.55f, 19.18f, 59.18f, 10.2f, 57.14f, 2.45f, 49.8f, 0f)),
        BodyShape(BodyRegion.ABDUCTORS, floatArrayOf(52.65f, 110.2f, 54.29f, 124.9f, 60f, 110.2f, 62.04f, 100f, 64.9f, 94.29f, 60f, 92.65f, 56.73f, 104.49f)),
        BodyShape(BodyRegion.ABDUCTORS, floatArrayOf(47.76f, 110.61f, 44.9f, 125.31f, 42.04f, 115.92f, 40.41f, 113.06f, 39.59f, 107.35f, 37.96f, 102.45f, 34.69f, 93.88f, 39.59f, 92.24f, 41.63f, 99.18f, 43.67f, 105.31f)),
        BodyShape(BodyRegion.QUADRICEPS, floatArrayOf(34.69f, 98.78f, 37.14f, 108.16f, 37.14f, 127.76f, 34.29f, 137.14f, 31.02f, 132.65f, 29.39f, 120f, 28.16f, 111.43f, 29.39f, 100.82f, 32.24f, 94.69f)),
        BodyShape(BodyRegion.QUADRICEPS, floatArrayOf(63.27f, 105.71f, 64.49f, 100f, 66.94f, 94.69f, 70.2f, 101.22f, 71.02f, 111.84f, 68.16f, 133.06f, 65.31f, 137.55f, 62.45f, 128.57f, 62.04f, 111.43f)),
        BodyShape(BodyRegion.QUADRICEPS, floatArrayOf(38.78f, 129.39f, 38.37f, 112.24f, 41.22f, 118.37f, 44.49f, 129.39f, 42.86f, 135.1f, 40f, 146.12f, 36.33f, 146.53f, 35.51f, 140f)),
        BodyShape(BodyRegion.QUADRICEPS, floatArrayOf(59.59f, 145.71f, 55.51f, 128.98f, 60.82f, 113.88f, 61.22f, 130.2f, 64.08f, 139.59f, 62.86f, 146.53f)),
        BodyShape(BodyRegion.QUADRICEPS, floatArrayOf(32.65f, 138.37f, 26.53f, 145.71f, 25.71f, 136.73f, 25.71f, 127.35f, 26.94f, 114.29f, 29.39f, 133.47f)),
        BodyShape(BodyRegion.QUADRICEPS, floatArrayOf(71.84f, 113.06f, 73.88f, 124.08f, 73.88f, 140.41f, 72.65f, 145.71f, 66.53f, 138.37f, 70.2f, 133.47f)),
        BodyShape(BodyRegion.KNEES, floatArrayOf(33.88f, 140f, 34.69f, 143.27f, 35.51f, 147.35f, 36.33f, 151.02f, 35.1f, 156.73f, 29.8f, 156.73f, 27.35f, 152.65f, 27.35f, 147.35f, 30.2f, 144.08f)),
        BodyShape(BodyRegion.KNEES, floatArrayOf(65.71f, 140f, 72.24f, 147.76f, 72.24f, 152.24f, 69.8f, 157.14f, 64.9f, 156.73f, 62.86f, 151.02f)),
        BodyShape(BodyRegion.CALVES, floatArrayOf(71.43f, 160.41f, 73.47f, 153.47f, 76.73f, 161.22f, 79.59f, 167.76f, 78.37f, 187.76f, 79.59f, 195.51f, 74.69f, 195.51f)),
        BodyShape(BodyRegion.CALVES, floatArrayOf(24.9f, 194.69f, 27.76f, 164.9f, 28.16f, 160.41f, 26.12f, 154.29f, 24.9f, 157.55f, 22.45f, 161.63f, 20.82f, 167.76f, 22.04f, 188.16f, 20.82f, 195.51f)),
        BodyShape(BodyRegion.CALVES, floatArrayOf(72.65f, 195.1f, 69.8f, 159.18f, 65.31f, 158.37f, 64.08f, 162.45f, 64.08f, 165.31f, 65.71f, 177.14f)),
        BodyShape(BodyRegion.CALVES, floatArrayOf(35.51f, 158.37f, 35.92f, 162.45f, 35.92f, 166.94f, 35.1f, 172.24f, 35.1f, 176.73f, 32.24f, 182.04f, 30.61f, 187.35f, 26.94f, 194.69f, 27.35f, 187.76f, 28.16f, 180.41f, 28.57f, 175.51f, 28.98f, 169.8f, 29.8f, 164.08f, 30.2f, 158.78f)),
        BodyShape(BodyRegion.FOREARMS, floatArrayOf(6.12f, 88.57f, 10.2f, 75.1f, 14.69f, 70.2f, 16.33f, 74.29f, 19.18f, 73.47f, 4.49f, 97.55f, 0f, 100f)),
        BodyShape(BodyRegion.FOREARMS, floatArrayOf(84.49f, 69.8f, 83.27f, 73.47f, 80f, 73.06f, 95.1f, 98.37f, 100f, 100.41f, 93.47f, 89.39f, 89.8f, 76.33f)),
        BodyShape(BodyRegion.FOREARMS, floatArrayOf(77.55f, 72.24f, 77.55f, 77.55f, 80.41f, 84.08f, 85.31f, 89.8f, 92.24f, 101.22f, 94.69f, 99.59f)),
        BodyShape(BodyRegion.FOREARMS, floatArrayOf(6.94f, 101.22f, 13.47f, 90.61f, 18.78f, 84.08f, 21.63f, 77.14f, 21.22f, 71.84f, 4.9f, 98.78f)),
    )

    val back: List<BodyShape> = listOf(
        BodyShape(BodyRegion.HEAD, floatArrayOf(50.64f, 0f, 45.96f, 0.85f, 40.85f, 5.53f, 40.43f, 12.77f, 45.11f, 20f, 55.74f, 20f, 59.15f, 13.62f, 59.57f, 4.68f, 55.74f, 1.28f)),
        BodyShape(BodyRegion.TRAPEZIUS, floatArrayOf(44.68f, 21.7f, 47.66f, 21.7f, 47.23f, 38.3f, 47.66f, 64.68f, 38.3f, 53.19f, 35.32f, 40.85f, 31.06f, 36.6f, 39.15f, 33.19f, 43.83f, 27.23f)),
        BodyShape(BodyRegion.TRAPEZIUS, floatArrayOf(52.34f, 21.7f, 55.74f, 21.7f, 56.6f, 27.23f, 60.85f, 32.77f, 68.94f, 36.6f, 64.68f, 40.43f, 61.7f, 53.19f, 52.34f, 64.68f, 53.19f, 38.3f)),
        BodyShape(BodyRegion.BACK_DELTOIDS, floatArrayOf(29.36f, 37.02f, 22.98f, 39.15f, 17.45f, 44.26f, 18.3f, 53.62f, 24.26f, 49.36f, 27.23f, 46.38f)),
        BodyShape(BodyRegion.BACK_DELTOIDS, floatArrayOf(71.06f, 37.02f, 78.3f, 39.57f, 82.55f, 44.68f, 81.7f, 53.62f, 74.89f, 48.94f, 72.34f, 45.11f)),
        BodyShape(BodyRegion.UPPER_BACK, floatArrayOf(31.06f, 38.72f, 28.09f, 48.94f, 28.51f, 55.32f, 34.04f, 75.32f, 47.23f, 71.06f, 47.23f, 66.38f, 36.6f, 54.04f, 33.62f, 41.28f)),
        BodyShape(BodyRegion.UPPER_BACK, floatArrayOf(68.94f, 38.72f, 71.91f, 49.36f, 71.49f, 56.17f, 65.96f, 75.32f, 52.77f, 71.06f, 52.77f, 66.38f, 63.4f, 54.47f, 66.38f, 41.7f)),
        BodyShape(BodyRegion.TRICEPS, floatArrayOf(26.81f, 49.79f, 17.87f, 55.74f, 14.47f, 72.34f, 16.6f, 81.7f, 21.7f, 63.83f, 26.81f, 55.74f)),
        BodyShape(BodyRegion.TRICEPS, floatArrayOf(73.62f, 50.21f, 82.13f, 55.74f, 85.96f, 73.19f, 83.4f, 82.13f, 77.87f, 62.98f, 73.19f, 55.74f)),
        BodyShape(BodyRegion.TRICEPS, floatArrayOf(26.81f, 58.3f, 26.81f, 68.51f, 22.98f, 75.32f, 19.15f, 77.45f, 22.55f, 65.53f)),
        BodyShape(BodyRegion.TRICEPS, floatArrayOf(72.77f, 58.3f, 77.02f, 64.68f, 80.43f, 77.45f, 76.6f, 75.32f, 72.77f, 68.94f)),
        BodyShape(BodyRegion.LOWER_BACK, floatArrayOf(47.66f, 72.77f, 34.47f, 77.02f, 35.32f, 83.4f, 49.36f, 102.13f, 46.81f, 82.98f)),
        BodyShape(BodyRegion.LOWER_BACK, floatArrayOf(52.34f, 72.77f, 65.53f, 77.02f, 64.68f, 83.4f, 50.64f, 102.13f, 53.19f, 83.83f)),
        BodyShape(BodyRegion.FOREARMS, floatArrayOf(86.38f, 75.74f, 91.06f, 83.4f, 93.19f, 94.04f, 100f, 106.38f, 96.17f, 104.26f, 88.09f, 89.36f, 84.26f, 83.83f)),
        BodyShape(BodyRegion.FOREARMS, floatArrayOf(13.62f, 75.74f, 8.94f, 83.83f, 6.81f, 93.62f, 0f, 106.38f, 3.83f, 104.26f, 12.34f, 88.51f, 15.74f, 82.98f)),
        BodyShape(BodyRegion.FOREARMS, floatArrayOf(81.28f, 79.57f, 77.45f, 77.87f, 79.15f, 84.68f, 91.06f, 103.83f, 93.19f, 108.94f, 94.47f, 104.68f)),
        BodyShape(BodyRegion.FOREARMS, floatArrayOf(18.72f, 79.57f, 22.13f, 77.87f, 20.85f, 84.26f, 9.36f, 102.98f, 6.81f, 108.51f, 5.11f, 104.68f)),
        BodyShape(BodyRegion.GLUTES, floatArrayOf(44.68f, 99.57f, 30.21f, 108.51f, 29.79f, 118.72f, 31.49f, 125.96f, 47.23f, 121.28f, 49.36f, 114.89f)),
        BodyShape(BodyRegion.GLUTES, floatArrayOf(55.32f, 99.15f, 51.06f, 114.47f, 52.34f, 120.85f, 68.09f, 125.96f, 69.79f, 119.15f, 69.36f, 108.51f)),
        BodyShape(BodyRegion.ADDUCTORS, floatArrayOf(48.09f, 122.98f, 44.68f, 122.98f, 41.28f, 125.53f, 45.11f, 144.26f, 48.51f, 135.74f, 48.94f, 129.36f)),
        BodyShape(BodyRegion.ADDUCTORS, floatArrayOf(51.91f, 122.55f, 55.74f, 123.4f, 59.15f, 125.96f, 54.89f, 144.26f, 51.91f, 136.17f, 51.06f, 129.36f)),
        BodyShape(BodyRegion.HAMSTRINGS, floatArrayOf(28.94f, 122.13f, 31.06f, 129.36f, 36.6f, 125.96f, 35.32f, 135.32f, 34.47f, 150.21f, 29.36f, 158.3f, 28.94f, 146.81f, 27.66f, 141.28f, 27.23f, 131.49f)),
        BodyShape(BodyRegion.HAMSTRINGS, floatArrayOf(71.49f, 121.7f, 69.36f, 128.94f, 63.83f, 125.96f, 65.53f, 136.6f, 66.38f, 150.21f, 71.06f, 158.3f, 71.49f, 147.66f, 72.77f, 142.13f, 73.62f, 131.91f)),
        BodyShape(BodyRegion.HAMSTRINGS, floatArrayOf(38.72f, 125.53f, 44.26f, 145.96f, 40.43f, 166.81f, 36.17f, 152.77f, 37.02f, 135.32f)),
        BodyShape(BodyRegion.HAMSTRINGS, floatArrayOf(61.7f, 125.53f, 63.4f, 136.17f, 64.26f, 153.19f, 60f, 166.81f, 56.17f, 146.38f)),
        BodyShape(BodyRegion.KNEES, floatArrayOf(34.47f, 153.19f, 31.06f, 159.15f, 33.62f, 166.38f, 37.45f, 162.55f)),
        BodyShape(BodyRegion.KNEES, floatArrayOf(66.38f, 153.62f, 62.98f, 162.98f, 66.81f, 166.38f, 69.36f, 159.15f)),
        BodyShape(BodyRegion.CALVES, floatArrayOf(29.36f, 160.43f, 28.51f, 167.23f, 24.68f, 179.57f, 23.83f, 192.77f, 25.53f, 197.02f, 28.51f, 193.19f, 29.79f, 180f, 31.91f, 171.06f, 31.91f, 166.81f)),
        BodyShape(BodyRegion.CALVES, floatArrayOf(37.45f, 165.11f, 35.32f, 167.66f, 33.19f, 171.91f, 31.06f, 180.43f, 30.21f, 191.91f, 34.04f, 200f, 38.72f, 190.64f, 39.15f, 168.94f)),
        BodyShape(BodyRegion.CALVES, floatArrayOf(62.98f, 165.11f, 61.28f, 168.51f, 61.7f, 190.64f, 66.38f, 199.57f, 70.64f, 191.91f, 68.94f, 179.57f, 66.81f, 170.21f)),
        BodyShape(BodyRegion.CALVES, floatArrayOf(70.64f, 160.43f, 72.34f, 168.51f, 75.74f, 179.15f, 76.6f, 192.77f, 74.47f, 196.6f, 72.34f, 193.62f, 70.64f, 179.57f, 68.09f, 168.09f)),
        BodyShape(BodyRegion.SOLEUS, floatArrayOf(28.51f, 195.74f, 30.21f, 195.74f, 33.62f, 201.7f, 30.64f, 220f, 28.51f, 213.62f, 26.81f, 198.3f)),
        BodyShape(BodyRegion.SOLEUS, floatArrayOf(69.79f, 195.74f, 71.91f, 195.74f, 73.62f, 198.3f, 71.91f, 213.19f, 70.21f, 219.57f, 67.23f, 202.13f)),
    )
}
